/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIClientAssociateEmployee.java
 *
 * Created on 06-01-2011, 10:40:49
 */
package GUILayer;

import ControlLayer.CtrClient;
import ControlLayer.CtrEmp;
import ModelLayer.Client;
import ModelLayer.Employee;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Erik
 */
public class GUIClientAssociateEmployee extends javax.swing.JPanel {

    /** Creates new form GUIClientAssociateEmployee */
    public GUIClientAssociateEmployee() {
        initComponents();
    }

    public void populateCmbEmployee() {
        CtrEmp ctrEmp = new CtrEmp();
        ArrayList<Employee> employeeList = ctrEmp.getAllEmployee();
        cmbEmployee.removeAllItems();
        cmbEmployee.insertItemAt("Vælg her", 0);
        for (Employee e : employeeList) {
            cmbEmployee.addItem(e);
        }
        cmbEmployee.removeItem("Vælg her");
    }

    public void populateCmbClient() {
        CtrClient CtrClient = new CtrClient();
        ArrayList<Client> clientList = CtrClient.getAllClients();
        cmbClient.removeAllItems();
        cmbClient.insertItemAt("Vælg her", 0);
        for (Client c : clientList) {
            cmbClient.addItem(c);
        }
        cmbClient.removeItem("Vælg her");
    }

    public void associateClientToEmployee() {
        try {
            CtrEmp ctrEmp = new CtrEmp();
            Employee e = (Employee) cmbEmployee.getSelectedItem();
            Client c = (Client) cmbClient.getSelectedItem();
            int employeeID = e.getEmployeeID();
            int clientID = c.getClientID();
            ctrEmp.associateClientToEmployee(employeeID, clientID);
        } catch (NullPointerException nPE) {
            JOptionPane.showMessageDialog(this, "Vælg venligst en medarbejder/klient");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void associateAllClientsToEmployee() {
        try {
            CtrEmp ctrEmp = new CtrEmp();
            Employee e = (Employee) cmbEmployee.getSelectedItem();
            int employeeID = e.getEmployeeID();
            int index = 0;
            while (index < cmbClient.getItemCount()) {
                Client c = (Client) cmbClient.getItemAt(index);
                int clientID = c.getClientID();

                ctrEmp.associateClientToEmployee(employeeID, clientID);
                index++;
            }
        } catch (NullPointerException nPE) {
            JOptionPane.showMessageDialog(this, "Vælg venligst en medarbejder/klient");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void disassociateClientFromEmployee() {
        try {
            CtrEmp ctrEmp = new CtrEmp();
            Employee e = (Employee) cmbEmployee.getSelectedItem();
            int employeeID = e.getEmployeeID();
            Client c = (Client) cmbClient.getSelectedItem();
            int clientID = c.getClientID();
            ctrEmp.disassociateClientFromEmployee(employeeID, clientID);
        } catch (NullPointerException nPE) {
            JOptionPane.showMessageDialog(this, "Vælg venligst en medarbejder/klient");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void disassociateAllClientsFromEmployee() {
        try {
            CtrEmp ctrEmp = new CtrEmp();
            int index = 0;
            while (index < cmbClient.getItemCount()) {
                Client c = (Client) cmbClient.getItemAt(index);
                int clientID = c.getClientID();
                Employee e = (Employee) cmbEmployee.getSelectedItem();
                int employeeID = e.getEmployeeID();
                ctrEmp.disassociateClientFromEmployee(employeeID, clientID);
                index++;
            }
        } catch (NullPointerException nPE) {
            JOptionPane.showMessageDialog(this, "Vælg venligst en medarbejder/klient");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbEmployee = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbClient = new javax.swing.JComboBox();
        btnAddAll = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemoveAll = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Vælg medarbejder");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbEmployee, javax.swing.GroupLayout.Alignment.TRAILING, 0, 237, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Vælg klient");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbClient, 0, 230, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        btnAddAll.setText("Tilføj alle");
        btnAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllActionPerformed(evt);
            }
        });

        btnAdd.setText("Tilføj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemoveAll.setText("Slet alle");
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });

        btnRemove.setText("Slet");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAddAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(btnAdd)
                    .addComponent(btnAddAll)
                    .addComponent(btnRemoveAll))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        associateClientToEmployee();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        disassociateClientFromEmployee();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllActionPerformed
        // TODO add your handling code here:
        associateAllClientsToEmployee();
    }//GEN-LAST:event_btnAddAllActionPerformed

    private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
        // TODO add your handling code here:
        disassociateAllClientsFromEmployee();
    }//GEN-LAST:event_btnRemoveAllActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddAll;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.JComboBox cmbClient;
    private javax.swing.JComboBox cmbEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
