/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on 10-12-2010, 09:35:24
 */

package GUILayer;

/**
 *
 * @author Glerup
 */
public class NewJPanel extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCreateEmployee = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnCreateEmployee.setText("Opret");
        btnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(btnCreateEmployee)
                .addGap(126, 126, 126))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeActionPerformed
        // TODO add your handling code here:
        String password = txtEmployeePassword.getText();
        String managerNo = txtEmployeeManagerNo.getText();
        String address = txtEmployeeAddress.getText();
        String city = txtEmployeeCity.getText();
        String email = txtEmployeeEmail.getText();
        String firstName = txtEmployeeFirstName.getText();
        String middleName = txtEmployeeMiddleName.getText();
        String lastName = txtEmployeeLastName.getText();
        int phoneNo = Integer.parseInt(txtEmployeePhoneNo.getText());
        String jobTitle = txtEmployeeJobTitle.getText();
        String ssn = txtEmployeeSsn.getText();
        int zipCode = Integer.parseInt(txtEmployeeZipCode.getText());
        String crudEmployee = "No";
        if(checkBoxCrudEmployee.isSelected()){
            crudEmployee = "Yes";
        }
        String crudClient = "No";
        if(checkBoxCrudClient.isSelected()){
            crudClient = "Yes";
        }
        String crudMedicine = "No";
        if(checkBoxCrudMedicine.isSelected()){
            crudMedicine = "Yes";
        }
        String crudCar = "No";
        if(checkBoxCrudCar.isSelected()){
            crudCar = "Yes";
        }
        String inUse = "No";
        if(checkBoxInUse.isSelected()){
            inUse = "Yes";
        }
        CtrEmp ctrEmp = new CtrEmp();
        CtrLoca ctrLoca = new CtrLoca();
        int locationID = ctrLoca.findLocationByZipCode(zipCode).getLocationID();
        ctrEmp.insert(managerNo, jobTitle, crudClient, crudEmployee, crudMedicine, crudCar, ssn, firstName, middleName, lastName, address, locationID, phoneNo, email, password);
}//GEN-LAST:event_btnCreateEmployeeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEmployee;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
