/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 19-10-2010, 10:05:03
 */
package GUILayer;

import ControlLayer.CtrEmp;
import ModelLayer.Employee;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Anita
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpGUI = new javax.swing.JTabbedPane();
        pLogin = new javax.swing.JPanel();
        txtBrugernavn = new javax.swing.JTextField();
        lblBrugernavn = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnNulstilLogin = new javax.swing.JButton();
        picKeyLogin = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        pKlienter = new javax.swing.JPanel();
        pBiler = new javax.swing.JPanel();
        pMedarbejdere = new javax.swing.JPanel();
        pHjælp = new javax.swing.JPanel();
        spHjælp = new javax.swing.JScrollPane();
        txtaHjælp = new javax.swing.JTextArea();
        txtIndtastHjælp = new javax.swing.JTextField();
        btnSøg = new javax.swing.JButton();
        pLogud = new javax.swing.JPanel();
        lblLogud = new javax.swing.JLabel();
        btnLogud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tpGUI.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tpGUI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tpGUI.setEnabled(false);
        tpGUI.setPreferredSize(new java.awt.Dimension(800, 600));

        txtBrugernavn.setToolTipText("Skriv dit brugernavn her");

        lblBrugernavn.setText("Brugernavn");

        lblPassword.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnNulstilLogin.setText("Nulstil");
        btnNulstilLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNulstilLoginActionPerformed(evt);
            }
        });

        picKeyLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Glerup\\Desktop\\login_welcome.jpg")); // NOI18N

        txtPassword.setFont(new java.awt.Font("Bookshelf Symbol 7", 0, 11)); // NOI18N

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                        .addComponent(picKeyLogin)
                        .addGap(301, 301, 301))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBrugernavn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrugernavn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNulstilLogin))
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(270, 270, 270))))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(picKeyLogin)
                .addGap(59, 59, 59)
                .addComponent(lblBrugernavn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBrugernavn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addGap(4, 4, 4)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnNulstilLogin))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        tpGUI.addTab("Login", null, pLogin, "Her logger du ind");

        javax.swing.GroupLayout pKlienterLayout = new javax.swing.GroupLayout(pKlienter);
        pKlienter.setLayout(pKlienterLayout);
        pKlienterLayout.setHorizontalGroup(
            pKlienterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        pKlienterLayout.setVerticalGroup(
            pKlienterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        tpGUI.addTab("Klienter", null, pKlienter, "Her ser du dine klienter");

        javax.swing.GroupLayout pBilerLayout = new javax.swing.GroupLayout(pBiler);
        pBiler.setLayout(pBilerLayout);
        pBilerLayout.setHorizontalGroup(
            pBilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        pBilerLayout.setVerticalGroup(
            pBilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        tpGUI.addTab("Biler", null, pBiler, "Her reserverer du biler");

        javax.swing.GroupLayout pMedarbejdereLayout = new javax.swing.GroupLayout(pMedarbejdere);
        pMedarbejdere.setLayout(pMedarbejdereLayout);
        pMedarbejdereLayout.setHorizontalGroup(
            pMedarbejdereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        pMedarbejdereLayout.setVerticalGroup(
            pMedarbejdereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        tpGUI.addTab("Medarbejdere", null, pMedarbejdere, "Her håndterer du medarbejdere");

        txtaHjælp.setColumns(20);
        txtaHjælp.setEditable(false);
        txtaHjælp.setFont(new java.awt.Font("Verdana", 0, 14));
        txtaHjælp.setRows(5);
        spHjælp.setViewportView(txtaHjælp);

        txtIndtastHjælp.setText("Indtast søgeord her");
        txtIndtastHjælp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIndtastHjælpFocusGained(evt);
            }
        });

        btnSøg.setText("Søg");

        javax.swing.GroupLayout pHjælpLayout = new javax.swing.GroupLayout(pHjælp);
        pHjælp.setLayout(pHjælpLayout);
        pHjælpLayout.setHorizontalGroup(
            pHjælpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHjælpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHjælpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHjælpLayout.createSequentialGroup()
                        .addComponent(txtIndtastHjælp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSøg)
                        .addContainerGap())
                    .addComponent(spHjælp, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)))
        );
        pHjælpLayout.setVerticalGroup(
            pHjælpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHjælpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pHjælpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSøg)
                    .addComponent(txtIndtastHjælp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spHjælp, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpGUI.addTab("Hjælp", null, pHjælp, "Her kan du se efter hjælp til brug af systemet");

        lblLogud.setText("Er du sikker på du vil logge ud");

        btnLogud.setText("Logud");
        btnLogud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLogudLayout = new javax.swing.GroupLayout(pLogud);
        pLogud.setLayout(pLogudLayout);
        pLogudLayout.setHorizontalGroup(
            pLogudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogudLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(pLogudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogudLayout.createSequentialGroup()
                        .addComponent(lblLogud)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogudLayout.createSequentialGroup()
                        .addComponent(btnLogud)
                        .addGap(313, 313, 313))))
        );
        pLogudLayout.setVerticalGroup(
            pLogudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogudLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(lblLogud)
                .addGap(18, 18, 18)
                .addComponent(btnLogud)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        tpGUI.addTab("Logud", null, pLogud, "Her logger du ud");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIndtastHjælpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIndtastHjælpFocusGained
        // TODO add your handling code here:
        txtIndtastHjælp.setText("");
    }//GEN-LAST:event_txtIndtastHjælpFocusGained

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        CtrEmp ctrEmp = new CtrEmp();
        String user = txtBrugernavn.getText();
        String pass = txtPassword.getText();
        if(user.equals(ctrEmp.findEmployee(user).getEmployeeNo()) && pass.equals(ctrEmp.findEmployee(user).getPassword())) {
            tpGUI.setEnabled(true);
            txtPassword.setText("");
            JOptionPane.showMessageDialog(pLogin, "Du er nu logget ind");
        }
        else {
            txtPassword.setText("");
            JOptionPane.showMessageDialog(pLogin, "Du har indtastet brugernavn eller password forkert");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNulstilLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNulstilLoginActionPerformed
        // TODO add your handling code here:
        txtBrugernavn.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_btnNulstilLoginActionPerformed

    private void btnLogudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogudActionPerformed
        // TODO add your handling code here:
        tpGUI.setEnabled(false);
        pLogin.setVisible(true);
    }//GEN-LAST:event_btnLogudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try{
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                }
                catch(Exception e){

                }

                new GUI().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogud;
    private javax.swing.JButton btnNulstilLogin;
    private javax.swing.JButton btnSøg;
    private javax.swing.JLabel lblBrugernavn;
    private javax.swing.JLabel lblLogud;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel pBiler;
    private javax.swing.JPanel pHjælp;
    private javax.swing.JPanel pKlienter;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pLogud;
    private javax.swing.JPanel pMedarbejdere;
    private javax.swing.JLabel picKeyLogin;
    private javax.swing.JScrollPane spHjælp;
    private javax.swing.JTabbedPane tpGUI;
    private javax.swing.JTextField txtBrugernavn;
    private javax.swing.JTextField txtIndtastHjælp;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextArea txtaHjælp;
    // End of variables declaration//GEN-END:variables
}
