/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIToDo.java
 *
 * Created on 04-01-2011, 11:44:17
 */
package GUILayer;

import ControlLayer.CtrTodo;
import GUILayer.GUITodo;
import ModelLayer.Employee;
import ModelLayer.Todo;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Erik M. Gravesen
 */
public class GUITodo extends javax.swing.JPanel {

    private Employee loggedInEmployee;
    private String date;

    /** Creates new form GUIToDo */
    public GUITodo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pTodoManagement = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtATodo = new javax.swing.JTextArea();
        cmbSelectDate = new javax.swing.JComboBox();
        lblShowTodo = new javax.swing.JLabel();
        btnDeleteTodo = new javax.swing.JButton();
        btnUpdateTodo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtACreateTodo = new javax.swing.JTextArea();
        lblTodo = new javax.swing.JLabel();
        btnCreateTodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        txtATodo.setColumns(20);
        txtATodo.setLineWrap(true);
        txtATodo.setRows(5);
        jScrollPane1.setViewportView(txtATodo);

        cmbSelectDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectDateItemStateChanged(evt);
            }
        });

        lblShowTodo.setText("Dato:");

        btnDeleteTodo.setText("Slet");
        btnDeleteTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTodoActionPerformed(evt);
            }
        });

        btnUpdateTodo.setText("Opdater");
        btnUpdateTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pTodoManagementLayout = new javax.swing.GroupLayout(pTodoManagement);
        pTodoManagement.setLayout(pTodoManagementLayout);
        pTodoManagementLayout.setHorizontalGroup(
            pTodoManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTodoManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTodoManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTodoManagementLayout.createSequentialGroup()
                        .addComponent(lblShowTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSelectDate, 0, 685, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTodoManagementLayout.createSequentialGroup()
                        .addComponent(btnUpdateTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteTodo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
                .addContainerGap())
        );
        pTodoManagementLayout.setVerticalGroup(
            pTodoManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTodoManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTodoManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSelectDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTodoManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteTodo)
                    .addComponent(btnUpdateTodo))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aftaler", pTodoManagement);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFocusable(false);
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        txtACreateTodo.setColumns(20);
        txtACreateTodo.setLineWrap(true);
        txtACreateTodo.setRows(5);
        txtACreateTodo.setText("Skriv her");
        txtACreateTodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtACreateTodoFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(txtACreateTodo);

        lblTodo.setText("Todo");

        btnCreateTodo.setText("Opret");
        btnCreateTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTodoActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dato (yyyy/mm/dd):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .addComponent(btnCreateTodo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTodo))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateTodo))
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Oprettelse", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public Employee getLoggedInEmployee() {
        return loggedInEmployee;
    }

    public void setLoggedInEmployee(Employee loggedInEmployee) {
        this.loggedInEmployee = loggedInEmployee;
    }

    public void updateCmbSelectDate() {
                CtrTodo ctrTodo = new CtrTodo();
        ArrayList<Todo> todoList = ctrTodo.getAllTodo();
        cmbSelectDate.removeAllItems();
        cmbSelectDate.insertItemAt("", 0);
        for (Todo t : todoList) {
            cmbSelectDate.addItem(t);
        }
        cmbSelectDate.removeItemAt(0);
    }

    private void cmbSelectDateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectDateItemStateChanged
        // TODO add your handling code here:
        Todo t = (Todo) cmbSelectDate.getSelectedItem();
        if (t != null) {

            txtATodo.setText(t.getText());
        }
    }//GEN-LAST:event_cmbSelectDateItemStateChanged

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        CtrTodo ctrTodo = new CtrTodo();
        updateCmbSelectDate();
        Todo tObj = ctrTodo.findLatestTodo();
        int todoID = tObj.getTodoID();
        int index = 0;
        boolean found = false;

        while(index < cmbSelectDate.getItemCount() && !found) {
            Todo tObjCompare = (Todo)cmbSelectDate.getItemAt(index);
            int todoIDCompare = tObjCompare.getTodoID();
            if(todoID == todoIDCompare) {
                cmbSelectDate.setSelectedIndex(index);
                txtATodo.setText(tObj.getText());
                found = true;
            }
            index++;
        }
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if (jDateChooser1.getDate() != null) {
            Calendar calendar = jDateChooser1.getCalendar();
            jDateChooser1.getDate();
            String year = Integer.toString(calendar.get(Calendar.YEAR));
            String month = Integer.toString(calendar.get(Calendar.MONTH) + 1);
            if (calendar.get(Calendar.MONTH) + 1 < 10) {
                month = "0" + month;
            }
            String day = Integer.toString(calendar.get(Calendar.DATE));
            if (calendar.get(Calendar.DATE) + 1 < 10) {
                day = "0" + day;
            }
            date = year + "-" + month + "-" + day;
            //txtACreateTodo.setText(date1);
        } else {
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void btnCreateTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTodoActionPerformed
        // TODO add your handling code here:
        CtrTodo ctrTodo = new CtrTodo();
        String text = txtACreateTodo.getText();
        
        try {
            if(!date.equals("")) {
            ctrTodo.insertTodo(loggedInEmployee, date, text);
            txtATodo.setText("");
            txtACreateTodo.setText("");
            updateCmbSelectDate();
            JOptionPane.showMessageDialog(this, "Der blev oprettet en todo");
            }
            else{
                JOptionPane.showMessageDialog(this, "Vælg venligst en dato");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCreateTodoActionPerformed

    private void btnDeleteTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTodoActionPerformed
        // TODO add your handling code here:
        CtrTodo ctrTodo = new CtrTodo();
        Todo tObj = (Todo) cmbSelectDate.getSelectedItem();
        int index = cmbSelectDate.getSelectedIndex();
        cmbSelectDate.removeItemAt(index);
        txtATodo.setText("");
        int todoID = tObj.getTodoID();
        ctrTodo.deleteTodo(todoID);
    }//GEN-LAST:event_btnDeleteTodoActionPerformed

    private void btnUpdateTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTodoActionPerformed
        // TODO add your handling code here:
        try{
        CtrTodo ctrTodo = new CtrTodo();
        Todo tObj = (Todo) cmbSelectDate.getSelectedItem();
        int todoID = tObj.getTodoID();
        String todoDate = tObj.getDate();
        String text = txtATodo.getText();
        ctrTodo.updateTodo(todoID, loggedInEmployee, todoDate, text);
        tObj.setText(text);
        JOptionPane.showMessageDialog(this, "Todo med datoen " + tObj.getDate() + " blev opdateret");
        }
        catch(Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateTodoActionPerformed

    private void txtACreateTodoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtACreateTodoFocusGained
        // TODO add your handling code here:
        if(txtACreateTodo.getText().equals("Skriv her")) {
            txtACreateTodo.setText("");
        }
    }//GEN-LAST:event_txtACreateTodoFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTodo;
    private javax.swing.JButton btnDeleteTodo;
    private javax.swing.JButton btnUpdateTodo;
    private javax.swing.JComboBox cmbSelectDate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblShowTodo;
    private javax.swing.JLabel lblTodo;
    private javax.swing.JPanel pTodoManagement;
    private javax.swing.JTextArea txtACreateTodo;
    private javax.swing.JTextArea txtATodo;
    // End of variables declaration//GEN-END:variables
}
