use dm71_2
insert into location values (555, 'Scanning')
insert into location values (800, 'Høje Taastrup')
insert into location values (877, 'København C')
insert into location values (892, 'Sjælland USF P')
insert into location values (893, 'Sjælland USF B')
insert into location values (897, 'eBrevsprækken')
insert into location values (899, 'Kommuneservice')
insert into location values (900, 'København C')
insert into location values (910, 'København C')
insert into location values (929, 'København C')
insert into location values (999, 'København C')
insert into location values (1000, 'København K')
insert into location values (1001, 'København K')
insert into location values (1002, 'København K')
insert into location values (1003, 'København K')
insert into location values (1004, 'København K')
insert into location values (1005, 'København K')
insert into location values (1006, 'København K')
insert into location values (1007, 'København K')
insert into location values (1008, 'København K')
insert into location values (1009, 'København K')
insert into location values (1010, 'København K')
insert into location values (1011, 'København K')
insert into location values (1012, 'København K')
insert into location values (1013, 'København K')
insert into location values (1014, 'København K')
insert into location values (1015, 'København K')
insert into location values (1016, 'København K')
insert into location values (1017, 'København K')
insert into location values (1018, 'København K')
insert into location values (1019, 'København K')
insert into location values (1020, 'København K')
insert into location values (1021, 'København K')
insert into location values (1022, 'København K')
insert into location values (1023, 'København K')
insert into location values (1024, 'København K')
insert into location values (1025, 'København K')
insert into location values (1026, 'København K')
insert into location values (1045, 'København K')
insert into location values (1050, 'København K')
insert into location values (1051, 'København K')
insert into location values (1052, 'København K')
insert into location values (1053, 'København K')
insert into location values (1054, 'København K')
insert into location values (1055, 'København K')
insert into location values (1056, 'København K')
insert into location values (1057, 'København K')
insert into location values (1058, 'København K')
insert into location values (1059, 'København K')
insert into location values (1060, 'København K')
insert into location values (1061, 'København K')
insert into location values (1062, 'København K')
insert into location values (1063, 'København K')
insert into location values (1064, 'København K')
insert into location values (1065, 'København K')
insert into location values (1066, 'København K')
insert into location values (1067, 'København K')
insert into location values (1068, 'København K')
insert into location values (1069, 'København K')
insert into location values (1070, 'København K')
insert into location values (1071, 'København K')
insert into location values (1072, 'København K')
insert into location values (1073, 'København K')
insert into location values (1074, 'København K')
insert into location values (1092, 'København K')
insert into location values (1093, 'København K')
insert into location values (1095, 'København K')
insert into location values (1098, 'København K')
insert into location values (1100, 'København K')
insert into location values (1101, 'København K')
insert into location values (1102, 'København K')
insert into location values (1103, 'København K')
insert into location values (1104, 'København K')
insert into location values (1105, 'København K')
insert into location values (1106, 'København K')
insert into location values (1107, 'København K')
insert into location values (1110, 'København K')
insert into location values (1111, 'København K')
insert into location values (1112, 'København K')
insert into location values (1113, 'København K')
insert into location values (1114, 'København K')
insert into location values (1115, 'København K')
insert into location values (1116, 'København K')
insert into location values (1117, 'København K')
insert into location values (1118, 'København K')
insert into location values (1119, 'København K')
insert into location values (1120, 'København K')
insert into location values (1121, 'København K')
insert into location values (1122, 'København K')
insert into location values (1123, 'København K')
insert into location values (1124, 'København K')
insert into location values (1125, 'København K')
insert into location values (1126, 'København K')
insert into location values (1127, 'København K')
insert into location values (1128, 'København K')
insert into location values (1129, 'København K')
insert into location values (1130, 'København K')
insert into location values (1131, 'København K')
insert into location values (1140, 'København K')
insert into location values (1147, 'København K')
insert into location values (1148, 'København K')
insert into location values (1150, 'København K')
insert into location values (1151, 'København K')
insert into location values (1152, 'København K')
insert into location values (1153, 'København K')
insert into location values (1154, 'København K')
insert into location values (1155, 'København K')
insert into location values (1156, 'København K')
insert into location values (1157, 'København K')
insert into location values (1158, 'København K')
insert into location values (1159, 'København K')
insert into location values (1160, 'København K')
insert into location values (1161, 'København K')
insert into location values (1162, 'København K')
insert into location values (1163, 'København K')
insert into location values (1164, 'København K')
insert into location values (1165, 'København K')
insert into location values (1166, 'København K')
insert into location values (1167, 'København K')
insert into location values (1168, 'København K')
insert into location values (1169, 'København K')
insert into location values (1170, 'København K')
insert into location values (1171, 'København K')
insert into location values (1172, 'København K')
insert into location values (1173, 'København K')
insert into location values (1174, 'København K')
insert into location values (1175, 'København K')
insert into location values (1200, 'København K')
insert into location values (1201, 'København K')
insert into location values (1202, 'København K')
insert into location values (1203, 'København K')
insert into location values (1204, 'København K')
insert into location values (1205, 'København K')
insert into location values (1206, 'København K')
insert into location values (1207, 'København K')
insert into location values (1208, 'København K')
insert into location values (1209, 'København K')
insert into location values (1210, 'København K')
insert into location values (1211, 'København K')
insert into location values (1212, 'København K')
insert into location values (1213, 'København K')
insert into location values (1214, 'København K')
insert into location values (1215, 'København K')
insert into location values (1216, 'København K')
insert into location values (1217, 'København K')
insert into location values (1218, 'København K')
insert into location values (1219, 'København K')
insert into location values (1220, 'København K')
insert into location values (1221, 'København K')
insert into location values (1240, 'København K')
insert into location values (1250, 'København K')
insert into location values (1251, 'København K')
insert into location values (1252, 'København K')
insert into location values (1253, 'København K')
insert into location values (1254, 'København K')
insert into location values (1255, 'København K')
insert into location values (1256, 'København K')
insert into location values (1257, 'København K')
insert into location values (1258, 'København K')
insert into location values (1259, 'København K')
insert into location values (1260, 'København K')
insert into location values (1261, 'København K')
insert into location values (1263, 'København K')
insert into location values (1264, 'København K')
insert into location values (1265, 'København K')
insert into location values (1266, 'København K')
insert into location values (1267, 'København K')
insert into location values (1268, 'København K')
insert into location values (1270, 'København K')
insert into location values (1271, 'København K')
insert into location values (1291, 'København K')
insert into location values (1300, 'København K')
insert into location values (1301, 'København K')
insert into location values (1302, 'København K')
insert into location values (1303, 'København K')
insert into location values (1304, 'København K')
insert into location values (1306, 'København K')
insert into location values (1307, 'København K')
insert into location values (1308, 'København K')
insert into location values (1309, 'København K')
insert into location values (1310, 'København K')
insert into location values (1311, 'København K')
insert into location values (1312, 'København K')
insert into location values (1313, 'København K')
insert into location values (1314, 'København K')
insert into location values (1315, 'København K')
insert into location values (1316, 'København K')
insert into location values (1317, 'København K')
insert into location values (1318, 'København K')
insert into location values (1319, 'København K')
insert into location values (1320, 'København K')
insert into location values (1321, 'København K')
insert into location values (1322, 'København K')
insert into location values (1323, 'København K')
insert into location values (1324, 'København K')
insert into location values (1325, 'København K')
insert into location values (1326, 'København K')
insert into location values (1327, 'København K')
insert into location values (1328, 'København K')
insert into location values (1329, 'København K')
insert into location values (1349, 'København K')
insert into location values (1350, 'København K')
insert into location values (1352, 'København K')
insert into location values (1353, 'København K')
insert into location values (1354, 'København K')
insert into location values (1355, 'København K')
insert into location values (1356, 'København K')
insert into location values (1357, 'København K')
insert into location values (1358, 'København K')
insert into location values (1359, 'København K')
insert into location values (1360, 'København K')
insert into location values (1361, 'København K')
insert into location values (1362, 'København K')
insert into location values (1363, 'København K')
insert into location values (1364, 'København K')
insert into location values (1365, 'København K')
insert into location values (1366, 'København K')
insert into location values (1367, 'København K')
insert into location values (1368, 'København K')
insert into location values (1369, 'København K')
insert into location values (1370, 'København K')
insert into location values (1371, 'København K')
insert into location values (1400, 'København K')
insert into location values (1401, 'København K')
insert into location values (1402, 'København K')
insert into location values (1403, 'København K')
insert into location values (1404, 'København K')
insert into location values (1406, 'København K')
insert into location values (1407, 'København K')
insert into location values (1408, 'København K')
insert into location values (1409, 'København K')
insert into location values (1410, 'København K')
insert into location values (1411, 'København K')
insert into location values (1412, 'København K')
insert into location values (1413, 'København K')
insert into location values (1414, 'København K')
insert into location values (1415, 'København K')
insert into location values (1416, 'København K')
insert into location values (1417, 'København K')
insert into location values (1418, 'København K')
insert into location values (1419, 'København K')
insert into location values (1420, 'København K')
insert into location values (1421, 'København K')
insert into location values (1422, 'København K')
insert into location values (1423, 'København K')
insert into location values (1424, 'København K')
insert into location values (1425, 'København K')
insert into location values (1426, 'København K')
insert into location values (1427, 'København K')
insert into location values (1428, 'København K')
insert into location values (1429, 'København K')
insert into location values (1430, 'København K')
insert into location values (1431, 'København K')
insert into location values (1432, 'København K')
insert into location values (1433, 'København K')
insert into location values (1434, 'København K')
insert into location values (1435, 'København K')
insert into location values (1436, 'København K')
insert into location values (1437, 'København K')
insert into location values (1438, 'København K')
insert into location values (1439, 'København K')
insert into location values (1440, 'København K')
insert into location values (1441, 'København K')
insert into location values (1448, 'København K')
insert into location values (1450, 'København K')
insert into location values (1451, 'København K')
insert into location values (1452, 'København K')
insert into location values (1453, 'København K')
insert into location values (1454, 'København K')
insert into location values (1455, 'København K')
insert into location values (1456, 'København K')
insert into location values (1457, 'København K')
insert into location values (1458, 'København K')
insert into location values (1459, 'København K')
insert into location values (1460, 'København K')
insert into location values (1461, 'København K')
insert into location values (1462, 'København K')
insert into location values (1463, 'København K')
insert into location values (1464, 'København K')
insert into location values (1465, 'København K')
insert into location values (1466, 'København K')
insert into location values (1467, 'København K')
insert into location values (1468, 'København K')
insert into location values (1470, 'København K')
insert into location values (1471, 'København K')
insert into location values (1472, 'København K')
insert into location values (1473, 'København K')
insert into location values (1500, 'København V')
insert into location values (1501, 'København V')
insert into location values (1502, 'København V')
insert into location values (1503, 'København V')
insert into location values (1504, 'København V')
insert into location values (1505, 'København V')
insert into location values (1506, 'København V')
insert into location values (1507, 'København V')
insert into location values (1508, 'København V')
insert into location values (1509, 'København V')
insert into location values (1510, 'København V')
insert into location values (1532, 'København V')
insert into location values (1533, 'København V')
insert into location values (1550, 'København V')
insert into location values (1551, 'København V')
insert into location values (1552, 'København V')
insert into location values (1553, 'København V')
insert into location values (1554, 'København V')
insert into location values (1555, 'København V')
insert into location values (1556, 'København V')
insert into location values (1557, 'København V')
insert into location values (1558, 'København V')
insert into location values (1559, 'København V')
insert into location values (1560, 'København V')
insert into location values (1561, 'København V')
insert into location values (1562, 'København V')
insert into location values (1563, 'København V')
insert into location values (1564, 'København V')
insert into location values (1566, 'København V')
insert into location values (1567, 'København V')
insert into location values (1568, 'København V')
insert into location values (1569, 'København V')
insert into location values (1570, 'København V')
insert into location values (1571, 'København V')
insert into location values (1572, 'København V')
insert into location values (1573, 'København V')
insert into location values (1574, 'København V')
insert into location values (1575, 'København V')
insert into location values (1576, 'København V')
insert into location values (1577, 'København V')
insert into location values (1592, 'København V')
insert into location values (1599, 'København V')
insert into location values (1600, 'København V')
insert into location values (1601, 'København V')
insert into location values (1602, 'København V')
insert into location values (1603, 'København V')
insert into location values (1604, 'København V')
insert into location values (1605, 'København V')
insert into location values (1606, 'København V')
insert into location values (1607, 'København V')
insert into location values (1608, 'København V')
insert into location values (1609, 'København V')
insert into location values (1610, 'København V')
insert into location values (1611, 'København V')
insert into location values (1612, 'København V')
insert into location values (1613, 'København V')
insert into location values (1614, 'København V')
insert into location values (1615, 'København V')
insert into location values (1616, 'København V')
insert into location values (1617, 'København V')
insert into location values (1618, 'København V')
insert into location values (1619, 'København V')
insert into location values (1620, 'København V')
insert into location values (1621, 'København V')
insert into location values (1622, 'København V')
insert into location values (1623, 'København V')
insert into location values (1624, 'København V')
insert into location values (1630, 'København V')
insert into location values (1631, 'København V')
insert into location values (1632, 'København V')
insert into location values (1633, 'København V')
insert into location values (1634, 'København V')
insert into location values (1635, 'København V')
insert into location values (1640, 'København V')
insert into location values (1650, 'København V')
insert into location values (1651, 'København V')
insert into location values (1652, 'København V')
insert into location values (1653, 'København V')
insert into location values (1654, 'København V')
insert into location values (1655, 'København V')
insert into location values (1656, 'København V')
insert into location values (1657, 'København V')
insert into location values (1658, 'København V')
insert into location values (1659, 'København V')
insert into location values (1660, 'København V')
insert into location values (1661, 'København V')
insert into location values (1662, 'København V')
insert into location values (1663, 'København V')
insert into location values (1664, 'København V')
insert into location values (1665, 'København V')
insert into location values (1666, 'København V')
insert into location values (1667, 'København V')
insert into location values (1668, 'København V')
insert into location values (1669, 'København V')
insert into location values (1670, 'København V')
insert into location values (1671, 'København V')
insert into location values (1672, 'København V')
insert into location values (1673, 'København V')
insert into location values (1674, 'København V')
insert into location values (1675, 'København V')
insert into location values (1676, 'København V')
insert into location values (1677, 'København V')
insert into location values (1699, 'København V')
insert into location values (1700, 'København V')
insert into location values (1701, 'København V')
insert into location values (1702, 'København V')
insert into location values (1703, 'København V')
insert into location values (1704, 'København V')
insert into location values (1705, 'København V')
insert into location values (1706, 'København V')
insert into location values (1707, 'København V')
insert into location values (1708, 'København V')
insert into location values (1709, 'København V')
insert into location values (1710, 'København V')
insert into location values (1711, 'København V')
insert into location values (1712, 'København V')
insert into location values (1713, 'København V')
insert into location values (1714, 'København V')
insert into location values (1715, 'København V')
insert into location values (1716, 'København V')
insert into location values (1717, 'København V')
insert into location values (1718, 'København V')
insert into location values (1719, 'København V')
insert into location values (1720, 'København V')
insert into location values (1721, 'København V')
insert into location values (1722, 'København V')
insert into location values (1723, 'København V')
insert into location values (1724, 'København V')
insert into location values (1725, 'København V')
insert into location values (1726, 'København V')
insert into location values (1727, 'København V')
insert into location values (1728, 'København V')
insert into location values (1729, 'København V')
insert into location values (1730, 'København V')
insert into location values (1731, 'København V')
insert into location values (1732, 'København V')
insert into location values (1733, 'København V')
insert into location values (1734, 'København V')
insert into location values (1735, 'København V')
insert into location values (1736, 'København V')
insert into location values (1737, 'København V')
insert into location values (1738, 'København V')
insert into location values (1739, 'København V')
insert into location values (1748, 'København V')
insert into location values (1749, 'København V')
insert into location values (1750, 'København V')
insert into location values (1751, 'København V')
insert into location values (1752, 'København V')
insert into location values (1753, 'København V')
insert into location values (1754, 'København V')
insert into location values (1755, 'København V')
insert into location values (1756, 'København V')
insert into location values (1757, 'København V')
insert into location values (1758, 'København V')
insert into location values (1759, 'København V')
insert into location values (1760, 'København V')
insert into location values (1761, 'København V')
insert into location values (1762, 'København V')
insert into location values (1763, 'København V')
insert into location values (1764, 'København V')
insert into location values (1765, 'København V')
insert into location values (1766, 'København V')
insert into location values (1770, 'København V')
insert into location values (1771, 'København V')
insert into location values (1772, 'København V')
insert into location values (1773, 'København V')
insert into location values (1774, 'København V')
insert into location values (1775, 'København V')
insert into location values (1777, 'København V')
insert into location values (1778, 'København V')
insert into location values (1780, 'København V')
insert into location values (1782, 'København V')
insert into location values (1784, 'København V')
insert into location values (1785, 'København V')
insert into location values (1786, 'København V')
insert into location values (1787, 'København V')
insert into location values (1789, 'København V')
insert into location values (1790, 'København V')
insert into location values (1795, 'København V')
insert into location values (1799, 'København V')
insert into location values (1800, 'Frederiksberg C')
insert into location values (1801, 'Frederiksberg C')
insert into location values (1802, 'Frederiksberg C')
insert into location values (1803, 'Frederiksberg C')
insert into location values (1804, 'Frederiksberg C')
insert into location values (1805, 'Frederiksberg C')
insert into location values (1806, 'Frederiksberg C')
insert into location values (1807, 'Frederiksberg C')
insert into location values (1808, 'Frederiksberg C')
insert into location values (1809, 'Frederiksberg C')
insert into location values (1810, 'Frederiksberg C')
insert into location values (1811, 'Frederiksberg C')
insert into location values (1812, 'Frederiksberg C')
insert into location values (1813, 'Frederiksberg C')
insert into location values (1814, 'Frederiksberg C')
insert into location values (1815, 'Frederiksberg C')
insert into location values (1816, 'Frederiksberg C')
insert into location values (1817, 'Frederiksberg C')
insert into location values (1818, 'Frederiksberg C')
insert into location values (1819, 'Frederiksberg C')
insert into location values (1820, 'Frederiksberg C')
insert into location values (1822, 'Frederiksberg C')
insert into location values (1823, 'Frederiksberg C')
insert into location values (1824, 'Frederiksberg C')
insert into location values (1825, 'Frederiksberg C')
insert into location values (1826, 'Frederiksberg C')
insert into location values (1827, 'Frederiksberg C')
insert into location values (1828, 'Frederiksberg C')
insert into location values (1829, 'Frederiksberg C')
insert into location values (1835, 'Frederiksberg C')
insert into location values (1850, 'Frederiksberg C')
insert into location values (1851, 'Frederiksberg C')
insert into location values (1852, 'Frederiksberg C')
insert into location values (1853, 'Frederiksberg C')
insert into location values (1854, 'Frederiksberg C')
insert into location values (1855, 'Frederiksberg C')
insert into location values (1856, 'Frederiksberg C')
insert into location values (1857, 'Frederiksberg C')
insert into location values (1860, 'Frederiksberg C')
insert into location values (1861, 'Frederiksberg C')
insert into location values (1862, 'Frederiksberg C')
insert into location values (1863, 'Frederiksberg C')
insert into location values (1864, 'Frederiksberg C')
insert into location values (1865, 'Frederiksberg C')
insert into location values (1866, 'Frederiksberg C')
insert into location values (1867, 'Frederiksberg C')
insert into location values (1868, 'Frederiksberg C')
insert into location values (1870, 'Frederiksberg C')
insert into location values (1871, 'Frederiksberg C')
insert into location values (1872, 'Frederiksberg C')
insert into location values (1873, 'Frederiksberg C')
insert into location values (1874, 'Frederiksberg C')
insert into location values (1875, 'Frederiksberg C')
insert into location values (1876, 'Frederiksberg C')
insert into location values (1877, 'Frederiksberg C')
insert into location values (1878, 'Frederiksberg C')
insert into location values (1879, 'Frederiksberg C')
insert into location values (1900, 'Frederiksberg C')
insert into location values (1901, 'Frederiksberg C')
insert into location values (1902, 'Frederiksberg C')
insert into location values (1903, 'Frederiksberg C')
insert into location values (1904, 'Frederiksberg C')
insert into location values (1905, 'Frederiksberg C')
insert into location values (1906, 'Frederiksberg C')
insert into location values (1908, 'Frederiksberg C')
insert into location values (1909, 'Frederiksberg C')
insert into location values (1910, 'Frederiksberg C')
insert into location values (1911, 'Frederiksberg C')
insert into location values (1912, 'Frederiksberg C')
insert into location values (1913, 'Frederiksberg C')
insert into location values (1914, 'Frederiksberg C')
insert into location values (1915, 'Frederiksberg C')
insert into location values (1916, 'Frederiksberg C')
insert into location values (1917, 'Frederiksberg C')
insert into location values (1920, 'Frederiksberg C')
insert into location values (1921, 'Frederiksberg C')
insert into location values (1922, 'Frederiksberg C')
insert into location values (1923, 'Frederiksberg C')
insert into location values (1924, 'Frederiksberg C')
insert into location values (1925, 'Frederiksberg C')
insert into location values (1926, 'Frederiksberg C')
insert into location values (1927, 'Frederiksberg C')
insert into location values (1928, 'Frederiksberg C')
insert into location values (1931, 'Frederiksberg C')
insert into location values (1950, 'Frederiksberg C')
insert into location values (1951, 'Frederiksberg C')
insert into location values (1952, 'Frederiksberg C')
insert into location values (1953, 'Frederiksberg C')
insert into location values (1954, 'Frederiksberg C')
insert into location values (1955, 'Frederiksberg C')
insert into location values (1956, 'Frederiksberg C')
insert into location values (1957, 'Frederiksberg C')
insert into location values (1958, 'Frederiksberg C')
insert into location values (1959, 'Frederiksberg C')
insert into location values (1960, 'Frederiksberg C')
insert into location values (1961, 'Frederiksberg C')
insert into location values (1962, 'Frederiksberg C')
insert into location values (1963, 'Frederiksberg C')
insert into location values (1964, 'Frederiksberg C')
insert into location values (1965, 'Frederiksberg C')
insert into location values (1966, 'Frederiksberg C')
insert into location values (1967, 'Frederiksberg C')
insert into location values (1970, 'Frederiksberg C')
insert into location values (1971, 'Frederiksberg C')
insert into location values (1972, 'Frederiksberg C')
insert into location values (1973, 'Frederiksberg C')
insert into location values (1974, 'Frederiksberg C')
insert into location values (2000, 'Frederiksberg')
insert into location values (2100, 'København Ø')
insert into location values (2200, 'København N')
insert into location values (2300, 'København S')
insert into location values (2400, 'København NV')
insert into location values (2450, 'København SV')
insert into location values (2500, 'Valby')
insert into location values (2600, 'Glostrup')
insert into location values (2605, 'Brøndby')
insert into location values (2610, 'Rødovre')
insert into location values (2620, 'Albertslund')
insert into location values (2625, 'Vallensbæk')
insert into location values (2630, 'Taastrup')
insert into location values (2635, 'Ishøj')
insert into location values (2640, 'Hedehusene')
insert into location values (2650, 'Hvidovre')
insert into location values (2660, 'Brøndby Strand')
insert into location values (2665, 'Vallensbæk Strand')
insert into location values (2670, 'Greve')
insert into location values (2680, 'Solrød Strand')
insert into location values (2690, 'Karlslunde')
insert into location values (2700, 'Brønshøj')
insert into location values (2720, 'Vanløse')
insert into location values (2730, 'Herlev')
insert into location values (2740, 'Skovlunde')
insert into location values (2750, 'Ballerup')
insert into location values (2760, 'Måløv')
insert into location values (2765, 'Smørum')
insert into location values (2770, 'Kastrup')
insert into location values (2791, 'Dragør')
insert into location values (2800, 'Kongens Lyngby')
insert into location values (2820, 'Gentofte')
insert into location values (2830, 'Virum')
insert into location values (2840, 'Holte')
insert into location values (2850, 'Nærum')
insert into location values (2860, 'Søborg')
insert into location values (2870, 'Dyssegård ')
insert into location values (2880, 'Bagsværd')
insert into location values (2900, 'Hellerup')
insert into location values (2920, 'Charlottenlund')
insert into location values (2930, 'Klampenborg')
insert into location values (2942, 'Skodsborg')
insert into location values (2950, 'Vedbæk')
insert into location values (2960, 'Rungsted Kyst')
insert into location values (2970, 'Hørsholm')
insert into location values (2980, 'Kokkedal')
insert into location values (2990, 'Nivå')
insert into location values (3000, 'Helsingør')
insert into location values (3050, 'Humlebæk')
insert into location values (3060, 'Espergærde')
insert into location values (3070, 'Snekkersten')
insert into location values (3080, 'Tikøb')
insert into location values (3100, 'Hornbæk')
insert into location values (3120, 'Dronningmølle')
insert into location values (3140, 'Ålsgårde')
insert into location values (3150, 'Hellebæk')
insert into location values (3200, 'Helsinge')
insert into location values (3210, 'Vejby')
insert into location values (3220, 'Tisvildeleje')
insert into location values (3230, 'Græsted')
insert into location values (3250, 'Gilleleje')
insert into location values (3300, 'Frederiksværk')
insert into location values (3310, 'Ølsted')
insert into location values (3320, 'Skævinge')
insert into location values (3330, 'Gørløse')
insert into location values (3360, 'Liseleje')
insert into location values (3370, 'Melby')
insert into location values (3390, 'Hundested')
insert into location values (3400, 'Hillerød')
insert into location values (3450, 'Allerød')
insert into location values (3460, 'Birkerød')
insert into location values (3480, 'Fredensborg')
insert into location values (3490, 'Kvistgård')
insert into location values (3500, 'Værløse')
insert into location values (3520, 'Farum')
insert into location values (3540, 'Lynge')
insert into location values (3550, 'Slangerup')
insert into location values (3600, 'Frederikssund')
insert into location values (3630, 'Jægerspris')
insert into location values (3650, 'Ølstykke')
insert into location values (3660, 'Stenløse')
insert into location values (3670, 'Veksø Sjælland')
insert into location values (3700, 'Rønne')
insert into location values (3720, 'Aakirkeby')
insert into location values (3730, 'Nexø')
insert into location values (3740, 'Svaneke')
insert into location values (3751, 'Østermarie')
insert into location values (3760, 'Gudhjem')
insert into location values (3770, 'Allinge')
insert into location values (3782, 'Klemensker')
insert into location values (3790, 'Hasle')
insert into location values (4000, 'Roskilde')
insert into location values (4030, 'Tune')
insert into location values (4040, 'Jyllinge')
insert into location values (4050, 'Skibby')
insert into location values (4060, 'Kirke Såby')
insert into location values (4070, 'Kirke Hyllinge')
insert into location values (4100, 'Ringsted')
insert into location values (4105, 'Ringsted')
insert into location values (4129, 'Ringsted')
insert into location values (4130, 'Viby Sjælland')
insert into location values (4140, 'Borup')
insert into location values (4160, 'Herlufmagle')
insert into location values (4171, 'Glumsø')
insert into location values (4173, 'Fjenneslev')
insert into location values (4174, 'Jystrup Midtsj')
insert into location values (4180, 'Sorø')
insert into location values (4190, 'Munke Bjergby')
insert into location values (4200, 'Slagelse')
insert into location values (4220, 'Korsør')
insert into location values (4230, 'Skælskør')
insert into location values (4241, 'Vemmelev')
insert into location values (4242, 'Boeslunde')
insert into location values (4243, 'Rude')
insert into location values (4250, 'Fuglebjerg')
insert into location values (4261, 'Dalmose')
insert into location values (4262, 'Sandved')
insert into location values (4270, 'Høng')
insert into location values (4281, 'Gørlev')
insert into location values (4291, 'Ruds Vedby')
insert into location values (4293, 'Dianalund')
insert into location values (4295, 'Stenlille')
insert into location values (4296, 'Nyrup')
insert into location values (4300, 'Holbæk')
insert into location values (4320, 'Lejre')
insert into location values (4330, 'Hvalsø')
insert into location values (4340, 'Tølløse')
insert into location values (4350, 'Ugerløse')
insert into location values (4360, 'Kirke Eskilstrup')
insert into location values (4370, 'Store Merløse')
insert into location values (4390, 'Vipperød')
insert into location values (4400, 'Kalundborg')
insert into location values (4420, 'Regstrup')
insert into location values (4440, 'Mørkøv')
insert into location values (4450, 'Jyderup')
insert into location values (4460, 'Snertinge')
insert into location values (4470, 'Svebølle')
insert into location values (4480, 'Store Fuglede')
insert into location values (4490, 'Jerslev Sjælland')
insert into location values (4500, 'Nykøbing Sj')
insert into location values (4520, 'Svinninge')
insert into location values (4532, 'Gislinge')
insert into location values (4534, 'Hørve')
insert into location values (4540, 'Fårevejle')
insert into location values (4550, 'Asnæs')
insert into location values (4560, 'Vig')
insert into location values (4571, 'Grevinge')
insert into location values (4572, 'Nørre Asmindrup')
insert into location values (4573, 'Højby')
insert into location values (4581, 'Rørvig')
insert into location values (4583, 'Sjællands Odde')
insert into location values (4591, 'Føllenslev')
insert into location values (4592, 'Sejerø')
insert into location values (4593, 'Eskebjerg')
insert into location values (4600, 'Køge')
insert into location values (4621, 'Gadstrup')
insert into location values (4622, 'Havdrup')
insert into location values (4623, 'Lille Skensved')
insert into location values (4632, 'Bjæverskov')
insert into location values (4640, 'Faxe')
insert into location values (4652, 'Hårlev')
insert into location values (4653, 'Karise')
insert into location values (4654, 'Faxe Ladeplads')
insert into location values (4660, 'Store Heddinge')
insert into location values (4671, 'Strøby')
insert into location values (4672, 'Klippinge')
insert into location values (4673, 'Rødvig Stevns')
insert into location values (4681, 'Herfølge')
insert into location values (4682, 'Tureby')
insert into location values (4683, 'Rønnede')
insert into location values (4684, 'Holmegaard ')
insert into location values (4690, 'Haslev')
insert into location values (4700, 'Næstved')
insert into location values (4720, 'Præstø')
insert into location values (4733, 'Tappernøje')
insert into location values (4735, 'Mern')
insert into location values (4736, 'Karrebæksminde')
insert into location values (4750, 'Lundby')
insert into location values (4760, 'Vordingborg')
insert into location values (4771, 'Kalvehave')
insert into location values (4772, 'Langebæk')
insert into location values (4773, 'Stensved')
insert into location values (4780, 'Stege')
insert into location values (4791, 'Borre')
insert into location values (4792, 'Askeby')
insert into location values (4793, 'Bogø By')
insert into location values (4800, 'Nykøbing F')
insert into location values (4840, 'Nørre Alslev')
insert into location values (4850, 'Stubbekøbing')
insert into location values (4862, 'Guldborg')
insert into location values (4863, 'Eskilstrup')
insert into location values (4871, 'Horbelev')
insert into location values (4872, 'Idestrup')
insert into location values (4873, 'Væggerløse')
insert into location values (4874, 'Gedser')
insert into location values (4880, 'Nysted')
insert into location values (4891, 'Toreby L')
insert into location values (4892, 'Kettinge')
insert into location values (4894, 'Øster Ulslev')
insert into location values (4895, 'Errindlev')
insert into location values (4900, 'Nakskov')
insert into location values (4912, 'Harpelunde')
insert into location values (4913, 'Horslunde')
insert into location values (4920, 'Søllested')
insert into location values (4930, 'Maribo')
insert into location values (4941, 'Bandholm')
insert into location values (4943, 'Torrig L')
insert into location values (4944, 'Fejø')
insert into location values (4951, 'Nørreballe')
insert into location values (4952, 'Stokkemarke')
insert into location values (4953, 'Vesterborg')
insert into location values (4960, 'Holeby')
insert into location values (4970, 'Rødby')
insert into location values (4983, 'Dannemare')
insert into location values (4990, 'Sakskøbing')
insert into location values (4992, 'Midtsjælland USF P')
insert into location values (5000, 'Odense C')
insert into location values (5029, 'Odense C')
insert into location values (5100, 'Odense C')
insert into location values (5200, 'Odense V')
insert into location values (5210, 'Odense NV')
insert into location values (5220, 'Odense SØ')
insert into location values (5230, 'Odense M')
insert into location values (5240, 'Odense NØ')
insert into location values (5250, 'Odense SV')
insert into location values (5260, 'Odense S')
insert into location values (5270, 'Odense N')
insert into location values (5290, 'Marslev')
insert into location values (5300, 'Kerteminde')
insert into location values (5320, 'Agedrup')
insert into location values (5330, 'Munkebo')
insert into location values (5350, 'Rynkeby')
insert into location values (5370, 'Mesinge')
insert into location values (5380, 'Dalby')
insert into location values (5390, 'Martofte')
insert into location values (5400, 'Bogense')
insert into location values (5450, 'Otterup')
insert into location values (5462, 'Morud')
insert into location values (5463, 'Harndrup')
insert into location values (5464, 'Brenderup Fyn')
insert into location values (5466, 'Asperup')
insert into location values (5471, 'Søndersø')
insert into location values (5474, 'Veflinge')
insert into location values (5485, 'Skamby')
insert into location values (5491, 'Blommenslyst')
insert into location values (5492, 'Vissenbjerg')
insert into location values (5500, 'Middelfart')
insert into location values (5540, 'Ullerslev')
insert into location values (5550, 'Langeskov')
insert into location values (5560, 'Aarup')
insert into location values (5580, 'Nørre Aaby')
insert into location values (5591, 'Gelsted')
insert into location values (5592, 'Ejby')
insert into location values (5600, 'Faaborg')
insert into location values (5610, 'Assens')
insert into location values (5620, 'Glamsbjerg')
insert into location values (5631, 'Ebberup')
insert into location values (5642, 'Millinge')
insert into location values (5672, 'Broby')
insert into location values (5683, 'Haarby')
insert into location values (5690, 'Tommerup')
insert into location values (5700, 'Svendborg')
insert into location values (5750, 'Ringe')
insert into location values (5762, 'Vester Skerninge')
insert into location values (5771, 'Stenstrup')
insert into location values (5772, 'Kværndrup')
insert into location values (5792, 'Årslev')
insert into location values (5800, 'Nyborg')
insert into location values (5853, 'Ørbæk')
insert into location values (5854, 'Gislev')
insert into location values (5856, 'Ryslinge')
insert into location values (5863, 'Ferritslev Fyn')
insert into location values (5871, 'Frørup')
insert into location values (5874, 'Hesselager')
insert into location values (5881, 'Skårup Fyn')
insert into location values (5882, 'Vejstrup')
insert into location values (5883, 'Oure')
insert into location values (5884, 'Gudme')
insert into location values (5892, 'Gudbjerg Sydfyn')
insert into location values (5900, 'Rudkøbing')
insert into location values (5932, 'Humble')
insert into location values (5935, 'Bagenkop')
insert into location values (5953, 'Tranekær')
insert into location values (5960, 'Marstal')
insert into location values (5970, 'Ærøskøbing')
insert into location values (5985, 'Søby Ærø')
insert into location values (6000, 'Kolding')
insert into location values (6040, 'Egtved')
insert into location values (6051, 'Almind')
insert into location values (6052, 'Viuf')
insert into location values (6064, 'Jordrup')
insert into location values (6070, 'Christiansfeld')
insert into location values (6091, 'Bjert')
insert into location values (6092, 'Sønder Stenderup')
insert into location values (6093, 'Sjølund')
insert into location values (6094, 'Hejls')
insert into location values (6100, 'Haderslev')
insert into location values (6200, 'Aabenraa')
insert into location values (6230, 'Rødekro')
insert into location values (6240, 'Løgumkloster')
insert into location values (6261, 'Bredebro')
insert into location values (6270, 'Tønder')
insert into location values (6280, 'Højer')
insert into location values (6300, 'Gråsten')
insert into location values (6310, 'Broager')
insert into location values (6320, 'Egernsund')
insert into location values (6330, 'Padborg')
insert into location values (6340, 'Kruså')
insert into location values (6360, 'Tinglev')
insert into location values (6372, 'Bylderup-Bov')
insert into location values (6392, 'Bolderslev')
insert into location values (6400, 'Sønderborg')
insert into location values (6430, 'Nordborg')
insert into location values (6440, 'Augustenborg')
insert into location values (6470, 'Sydals')
insert into location values (6500, 'Vojens')
insert into location values (6510, 'Gram')
insert into location values (6520, 'Toftlund')
insert into location values (6534, 'Agerskov')
insert into location values (6535, 'Branderup J')
insert into location values (6541, 'Bevtoft')
insert into location values (6560, 'Sommersted')
insert into location values (6580, 'Vamdrup')
insert into location values (6600, 'Vejen')
insert into location values (6621, 'Gesten')
insert into location values (6622, 'Bække')
insert into location values (6623, 'Vorbasse')
insert into location values (6630, 'Rødding')
insert into location values (6640, 'Lunderskov')
insert into location values (6650, 'Brørup')
insert into location values (6660, 'Lintrup')
insert into location values (6670, 'Holsted')
insert into location values (6682, 'Hovborg')
insert into location values (6683, 'Føvling')
insert into location values (6690, 'Gørding')
insert into location values (6700, 'Esbjerg')
insert into location values (6701, 'Esbjerg')
insert into location values (6705, 'Esbjerg Ø')
insert into location values (6710, 'Esbjerg V')
insert into location values (6715, 'Esbjerg N')
insert into location values (6720, 'Fanø')
insert into location values (6731, 'Tjæreborg')
insert into location values (6740, 'Bramming')
insert into location values (6752, 'Glejbjerg')
insert into location values (6753, 'Agerbæk')
insert into location values (6760, 'Ribe')
insert into location values (6771, 'Gredstedbro')
insert into location values (6780, 'Skærbæk')
insert into location values (6792, 'Rømø')
insert into location values (6800, 'Varde')
insert into location values (6818, 'Årre')
insert into location values (6823, 'Ansager')
insert into location values (6830, 'Nørre Nebel')
insert into location values (6840, 'Oksbøl')
insert into location values (6851, 'Janderup Vestj')
insert into location values (6852, 'Billum')
insert into location values (6853, 'Vejers Strand')
insert into location values (6854, 'Henne')
insert into location values (6855, 'Outrup')
insert into location values (6857, 'Blåvand')
insert into location values (6862, 'Tistrup')
insert into location values (6870, 'Ølgod')
insert into location values (6880, 'Tarm')
insert into location values (6893, 'Hemmet')
insert into location values (6900, 'Skjern')
insert into location values (6920, 'Videbæk')
insert into location values (6933, 'Kibæk')
insert into location values (6940, 'Lem St')
insert into location values (6950, 'Ringkøbing')
insert into location values (6960, 'Hvide Sande')
insert into location values (6971, 'Spjald')
insert into location values (6973, 'Ørnhøj')
insert into location values (6980, 'Tim')
insert into location values (6990, 'Ulfborg')
insert into location values (7000, 'Fredericia')
insert into location values (7007, 'Fredericia')
insert into location values (7029, 'Fredericia')
insert into location values (7080, 'Børkop')
insert into location values (7100, 'Vejle')
insert into location values (7120, 'Vejle Øst')
insert into location values (7130, 'Juelsminde')
insert into location values (7140, 'Stouby')
insert into location values (7150, 'Barrit')
insert into location values (7160, 'Tørring')
insert into location values (7171, 'Uldum')
insert into location values (7173, 'Vonge')
insert into location values (7182, 'Bredsten')
insert into location values (7183, 'Randbøl')
insert into location values (7184, 'Vandel')
insert into location values (7190, 'Billund')
insert into location values (7200, 'Grindsted')
insert into location values (7250, 'Hejnsvig')
insert into location values (7260, 'Sønder Omme')
insert into location values (7270, 'Stakroge')
insert into location values (7280, 'Sønder Felding')
insert into location values (7300, 'Jelling')
insert into location values (7321, 'Gadbjerg')
insert into location values (7323, 'Give')
insert into location values (7330, 'Brande')
insert into location values (7361, 'Ejstrupholm')
insert into location values (7362, 'Hampen')
insert into location values (7400, 'Herning')
insert into location values (7429, 'Herning')
insert into location values (7430, 'Ikast')
insert into location values (7441, 'Bording')
insert into location values (7442, 'Engesvang')
insert into location values (7451, 'Sunds')
insert into location values (7470, 'Karup J')
insert into location values (7480, 'Vildbjerg')
insert into location values (7490, 'Aulum')
insert into location values (7500, 'Holstebro')
insert into location values (7540, 'Haderup')
insert into location values (7550, 'Sørvad')
insert into location values (7560, 'Hjerm')
insert into location values (7570, 'Vemb')
insert into location values (7600, 'Struer')
insert into location values (7620, 'Lemvig')
insert into location values (7650, 'Bøvlingbjerg')
insert into location values (7660, 'Bækmarksbro')
insert into location values (7673, 'Harboøre')
insert into location values (7680, 'Thyborøn')
insert into location values (7700, 'Thisted')
insert into location values (7730, 'Hanstholm')
insert into location values (7741, 'Frøstrup')
insert into location values (7742, 'Vesløs')
insert into location values (7752, 'Snedsted')
insert into location values (7755, 'Bedsted Thy')
insert into location values (7760, 'Hurup Thy')
insert into location values (7770, 'Vestervig')
insert into location values (7790, 'Thyholm')
insert into location values (7800, 'Skive')
insert into location values (7830, 'Vinderup')
insert into location values (7840, 'Højslev')
insert into location values (7850, 'Stoholm Jyll')
insert into location values (7860, 'Spøttrup')
insert into location values (7870, 'Roslev')
insert into location values (7884, 'Fur')
insert into location values (7900, 'Nykøbing M')
insert into location values (7950, 'Erslev')
insert into location values (7960, 'Karby')
insert into location values (7970, 'Redsted M')
insert into location values (7980, 'Vils')
insert into location values (7990, 'Øster Assels')
insert into location values (7992, 'Sydjylland/Fyn USF P')
insert into location values (7993, 'Sydjylland/Fyn USF B')
insert into location values (7996, 'Fakturaservice')
insert into location values (7997, 'Fakturascanning')
insert into location values (7999, 'Kommunepost')
insert into location values (8000, 'Århus C')
insert into location values (8100, 'Århus C')
insert into location values (8200, 'Århus N')
insert into location values (8210, 'Århus V')
insert into location values (8220, 'Brabrand')
insert into location values (8229, 'Risskov Ø')
insert into location values (8230, 'Åbyhøj')
insert into location values (8240, 'Risskov')
insert into location values (8245, 'Risskov Ø')
insert into location values (8250, 'Egå')
insert into location values (8260, 'Viby J')
insert into location values (8270, 'Højbjerg')
insert into location values (8300, 'Odder')
insert into location values (8305, 'Samsø')
insert into location values (8310, 'Tranbjerg J')
insert into location values (8320, 'Mårslet')
insert into location values (8330, 'Beder')
insert into location values (8340, 'Malling')
insert into location values (8350, 'Hundslund')
insert into location values (8355, 'Solbjerg')
insert into location values (8361, 'Hasselager')
insert into location values (8362, 'Hørning')
insert into location values (8370, 'Hadsten')
insert into location values (8380, 'Trige')
insert into location values (8381, 'Tilst')
insert into location values (8382, 'Hinnerup')
insert into location values (8400, 'Ebeltoft')
insert into location values (8410, 'Rønde')
insert into location values (8420, 'Knebel')
insert into location values (8444, 'Balle')
insert into location values (8450, 'Hammel')
insert into location values (8462, 'Harlev J')
insert into location values (8464, 'Galten')
insert into location values (8471, 'Sabro')
insert into location values (8472, 'Sporup')
insert into location values (8500, 'Grenaa')
insert into location values (8520, 'Lystrup')
insert into location values (8530, 'Hjortshøj')
insert into location values (8541, 'Skødstrup')
insert into location values (8543, 'Hornslet')
insert into location values (8544, 'Mørke')
insert into location values (8550, 'Ryomgård')
insert into location values (8560, 'Kolind')
insert into location values (8570, 'Trustrup')
insert into location values (8581, 'Nimtofte')
insert into location values (8585, 'Glesborg')
insert into location values (8586, 'Ørum Djurs')
insert into location values (8592, 'Anholt')
insert into location values (8600, 'Silkeborg')
insert into location values (8620, 'Kjellerup')
insert into location values (8632, 'Lemming')
insert into location values (8641, 'Sorring')
insert into location values (8643, 'Ans By')
insert into location values (8653, 'Them')
insert into location values (8654, 'Bryrup')
insert into location values (8660, 'Skanderborg')
insert into location values (8670, 'Låsby')
insert into location values (8680, 'Ry')
insert into location values (8700, 'Horsens')
insert into location values (8721, 'Daugård')
insert into location values (8722, 'Hedensted')
insert into location values (8723, 'Løsning')
insert into location values (8732, 'Hovedgård')
insert into location values (8740, 'Brædstrup')
insert into location values (8751, 'Gedved')
insert into location values (8752, 'Østbirk')
insert into location values (8762, 'Flemming')
insert into location values (8763, 'Rask Mølle')
insert into location values (8765, 'Klovborg')
insert into location values (8766, 'Nørre Snede')
insert into location values (8781, 'Stenderup')
insert into location values (8783, 'Hornsyld')
insert into location values (8800, 'Viborg')
insert into location values (8830, 'Tjele')
insert into location values (8831, 'Løgstrup')
insert into location values (8832, 'Skals')
insert into location values (8840, 'Rødkærsbro')
insert into location values (8850, 'Bjerringbro')
insert into location values (8860, 'Ulstrup')
insert into location values (8870, 'Langå')
insert into location values (8881, 'Thorsø')
insert into location values (8882, 'Fårvang')
insert into location values (8883, 'Gjern')
insert into location values (8900, 'Randers C')
insert into location values (8920, 'Randers NV')
insert into location values (8930, 'Randers NØ')
insert into location values (8940, 'Randers SV')
insert into location values (8950, 'Ørsted')
insert into location values (8960, 'Randers SØ')
insert into location values (8961, 'Allingåbro')
insert into location values (8963, 'Auning')
insert into location values (8970, 'Havndal')
insert into location values (8981, 'Spentrup')
insert into location values (8983, 'Gjerlev J')
insert into location values (8990, 'Fårup')
insert into location values (9000, 'Aalborg')
insert into location values (9029, 'Aalborg')
insert into location values (9100, 'Aalborg')
insert into location values (9200, 'Aalborg SV')
insert into location values (9210, 'Aalborg SØ')
insert into location values (9220, 'Aalborg Øst')
insert into location values (9230, 'Svenstrup J')
insert into location values (9240, 'Nibe')
insert into location values (9260, 'Gistrup')
insert into location values (9270, 'Klarup')
insert into location values (9280, 'Storvorde')
insert into location values (9293, 'Kongerslev')
insert into location values (9300, 'Sæby')
insert into location values (9310, 'Vodskov')
insert into location values (9320, 'Hjallerup')
insert into location values (9330, 'Dronninglund')
insert into location values (9340, 'Asaa')
insert into location values (9352, 'Dybvad')
insert into location values (9362, 'Gandrup')
insert into location values (9370, 'Hals')
insert into location values (9380, 'Vestbjerg')
insert into location values (9381, 'Sulsted')
insert into location values (9382, 'Tylstrup')
insert into location values (9400, 'Nørresundby')
insert into location values (9430, 'Vadum')
insert into location values (9440, 'Aabybro')
insert into location values (9460, 'Brovst')
insert into location values (9480, 'Løkken')
insert into location values (9490, 'Pandrup')
insert into location values (9492, 'Blokhus')
insert into location values (9493, 'Saltum')
insert into location values (9500, 'Hobro')
insert into location values (9510, 'Arden')
insert into location values (9520, 'Skørping')
insert into location values (9530, 'Støvring')
insert into location values (9541, 'Suldrup')
insert into location values (9550, 'Mariager')
insert into location values (9560, 'Hadsund')
insert into location values (9574, 'Bælum')
insert into location values (9575, 'Terndrup')
insert into location values (9600, 'Aars')
insert into location values (9610, 'Nørager')
insert into location values (9620, 'Aalestrup')
insert into location values (9631, 'Gedsted')
insert into location values (9632, 'Møldrup')
insert into location values (9640, 'Farsø')
insert into location values (9670, 'Løgstør')
insert into location values (9681, 'Ranum')
insert into location values (9690, 'Fjerritslev')
insert into location values (9700, 'Brønderslev')
insert into location values (9740, 'Jerslev J')
insert into location values (9750, 'Østervrå')
insert into location values (9760, 'Vrå')
insert into location values (9800, 'Hjørring')
insert into location values (9830, 'Tårs')
insert into location values (9850, 'Hirtshals')
insert into location values (9870, 'Sindal')
insert into location values (9881, 'Bindslev')
insert into location values (9900, 'Frederikshavn')
insert into location values (9940, 'Læsø')
insert into location values (9970, 'Strandby')
insert into location values (9981, 'Jerup')
insert into location values (9982, 'Ålbæk')
insert into location values (9990, 'Skagen')
insert into location values (9992, 'Jylland USF P')
insert into location values (9993, 'Jylland USF B')
insert into location values (9996, 'Fakturaservice')
insert into location values (9997, 'Fakturascanning')
insert into location values (9998, 'Borgerservice')
