INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (555, N'Scanning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (800, N'Høje Taastrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (877, N'København C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (892, N'Sjælland USF P')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (893, N'Sjælland USF B')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (897, N'eBrevsprækken')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (899, N'Kommuneservice')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (900, N'København C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (910, N'København C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (929, N'København C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (999, N'København C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1000, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1001, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1002, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1003, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1004, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1005, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1006, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1007, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1008, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1009, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1010, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1011, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1012, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1013, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1014, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1015, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1016, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1017, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1018, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1019, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1020, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1021, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1022, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1023, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1024, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1025, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1026, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1045, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1050, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1051, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1052, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1053, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1054, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1055, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1056, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1057, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1058, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1059, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1060, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1061, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1062, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1063, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1064, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1065, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1066, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1067, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1068, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1069, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1070, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1071, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1072, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1073, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1074, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1092, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1093, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1095, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1098, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1100, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1101, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1102, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1103, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1104, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1105, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1106, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1107, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1110, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1111, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1112, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1113, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1114, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1115, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1116, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1117, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1118, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1119, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1120, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1121, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1122, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1123, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1124, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1125, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1126, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1127, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1128, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1129, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1130, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1131, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1140, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1147, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1148, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1150, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1151, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1152, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1153, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1154, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1155, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1156, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1157, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1158, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1159, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1160, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1161, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1162, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1163, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1164, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1165, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1166, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1167, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1168, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1169, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1170, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1171, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1172, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1173, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1174, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1175, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1200, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1201, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1202, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1203, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1204, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1205, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1206, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1207, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1208, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1209, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1210, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1211, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1212, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1213, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1214, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1215, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1216, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1217, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1218, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1219, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1220, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1221, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1240, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1250, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1251, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1252, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1253, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1254, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1255, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1256, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1257, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1258, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1259, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1260, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1261, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1263, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1264, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1265, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1266, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1267, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1268, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1270, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1271, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1291, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1300, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1301, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1302, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1303, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1304, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1306, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1307, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1308, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1309, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1310, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1311, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1312, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1313, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1314, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1315, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1316, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1317, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1318, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1319, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1320, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1321, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1322, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1323, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1324, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1325, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1326, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1327, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1328, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1329, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1349, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1350, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1352, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1353, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1354, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1355, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1356, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1357, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1358, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1359, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1360, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1361, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1362, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1363, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1364, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1365, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1366, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1367, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1368, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1369, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1370, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1371, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1400, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1401, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1402, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1403, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1404, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1406, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1407, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1408, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1409, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1410, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1411, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1412, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1413, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1414, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1415, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1416, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1417, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1418, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1419, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1420, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1421, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1422, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1423, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1424, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1425, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1426, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1427, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1428, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1429, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1430, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1431, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1432, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1433, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1434, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1435, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1436, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1437, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1438, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1439, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1440, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1441, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1448, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1450, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1451, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1452, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1453, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1454, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1455, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1456, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1457, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1458, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1459, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1460, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1461, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1462, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1463, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1464, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1465, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1466, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1467, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1468, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1470, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1471, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1472, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1473, N'København K')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1500, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1501, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1502, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1503, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1504, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1505, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1506, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1507, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1508, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1509, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1510, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1532, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1533, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1550, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1551, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1552, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1553, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1554, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1555, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1556, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1557, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1558, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1559, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1560, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1561, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1562, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1563, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1564, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1566, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1567, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1568, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1569, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1570, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1571, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1572, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1573, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1574, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1575, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1576, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1577, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1592, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1599, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1600, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1601, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1602, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1603, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1604, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1605, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1606, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1607, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1608, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1609, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1610, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1611, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1612, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1613, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1614, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1615, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1616, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1617, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1618, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1619, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1620, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1621, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1622, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1623, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1624, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1630, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1631, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1632, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1633, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1634, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1635, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1640, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1650, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1651, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1652, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1653, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1654, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1655, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1656, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1657, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1658, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1659, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1660, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1661, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1662, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1663, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1664, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1665, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1666, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1667, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1668, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1669, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1670, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1671, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1672, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1673, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1674, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1675, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1676, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1677, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1699, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1700, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1701, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1702, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1703, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1704, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1705, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1706, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1707, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1708, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1709, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1710, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1711, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1712, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1713, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1714, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1715, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1716, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1717, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1718, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1719, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1720, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1721, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1722, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1723, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1724, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1725, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1726, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1727, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1728, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1729, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1730, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1731, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1732, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1733, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1734, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1735, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1736, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1737, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1738, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1739, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1748, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1749, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1750, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1751, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1752, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1753, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1754, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1755, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1756, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1757, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1758, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1759, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1760, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1761, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1762, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1763, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1764, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1765, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1766, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1770, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1771, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1772, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1773, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1774, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1775, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1777, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1778, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1780, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1782, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1784, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1785, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1786, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1787, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1789, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1790, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1795, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1799, N'København V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1800, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1801, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1802, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1803, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1804, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1805, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1806, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1807, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1808, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1809, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1810, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1811, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1812, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1813, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1814, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1815, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1816, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1817, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1818, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1819, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1820, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1822, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1823, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1824, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1825, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1826, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1827, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1828, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1829, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1835, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1850, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1851, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1852, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1853, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1854, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1855, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1856, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1857, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1860, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1861, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1862, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1863, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1864, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1865, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1866, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1867, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1868, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1870, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1871, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1872, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1873, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1874, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1875, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1876, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1877, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1878, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1879, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1900, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1901, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1902, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1903, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1904, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1905, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1906, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1908, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1909, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1910, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1911, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1912, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1913, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1914, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1915, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1916, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1917, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1920, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1921, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1922, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1923, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1924, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1925, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1926, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1927, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1928, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1931, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1950, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1951, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1952, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1953, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1954, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1955, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1956, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1957, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1958, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1959, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1960, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1961, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1962, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1963, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1964, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1965, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1966, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1967, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1970, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1971, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1972, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1973, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (1974, N'Frederiksberg C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2000, N'Frederiksberg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2100, N'København Ø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2200, N'København N')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2300, N'København S')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2400, N'København NV')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2450, N'København SV')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2500, N'Valby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2600, N'Glostrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2605, N'Brøndby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2610, N'Rødovre')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2620, N'Albertslund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2625, N'Vallensbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2630, N'Taastrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2635, N'Ishøj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2640, N'Hedehusene')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2650, N'Hvidovre')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2660, N'Brøndby Strand')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2665, N'Vallensbæk Strand')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2670, N'Greve')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2680, N'Solrød Strand')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2690, N'Karlslunde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2700, N'Brønshøj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2720, N'Vanløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2730, N'Herlev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2740, N'Skovlunde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2750, N'Ballerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2760, N'Måløv')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2765, N'Smørum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2770, N'Kastrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2791, N'Dragør')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2800, N'Kongens Lyngby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2820, N'Gentofte')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2830, N'Virum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2840, N'Holte')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2850, N'Nærum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2860, N'Søborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2870, N'Dyssegård ')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2880, N'Bagsværd')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2900, N'Hellerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2920, N'Charlottenlund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2930, N'Klampenborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2942, N'Skodsborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2950, N'Vedbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2960, N'Rungsted Kyst')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2970, N'Hørsholm')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2980, N'Kokkedal')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (2990, N'Nivå')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3000, N'Helsingør')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3050, N'Humlebæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3060, N'Espergærde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3070, N'Snekkersten')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3080, N'Tikøb')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3100, N'Hornbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3120, N'Dronningmølle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3140, N'Ålsgårde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3150, N'Hellebæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3200, N'Helsinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3210, N'Vejby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3220, N'Tisvildeleje')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3230, N'Græsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3250, N'Gilleleje')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3300, N'Frederiksværk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3310, N'Ølsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3320, N'Skævinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3330, N'Gørløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3360, N'Liseleje')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3370, N'Melby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3390, N'Hundested')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3400, N'Hillerød')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3450, N'Allerød')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3460, N'Birkerød')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3480, N'Fredensborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3490, N'Kvistgård')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3500, N'Værløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3520, N'Farum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3540, N'Lynge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3550, N'Slangerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3600, N'Frederikssund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3630, N'Jægerspris')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3650, N'Ølstykke')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3660, N'Stenløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3670, N'Veksø Sjælland')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3700, N'Rønne')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3720, N'Aakirkeby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3730, N'Nexø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3740, N'Svaneke')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3751, N'Østermarie')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3760, N'Gudhjem')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3770, N'Allinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3782, N'Klemensker')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (3790, N'Hasle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4000, N'Roskilde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4030, N'Tune')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4040, N'Jyllinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4050, N'Skibby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4060, N'Kirke Såby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4070, N'Kirke Hyllinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4100, N'Ringsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4105, N'Ringsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4129, N'Ringsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4130, N'Viby Sjælland')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4140, N'Borup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4160, N'Herlufmagle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4171, N'Glumsø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4173, N'Fjenneslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4174, N'Jystrup Midtsj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4180, N'Sorø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4190, N'Munke Bjergby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4200, N'Slagelse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4220, N'Korsør')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4230, N'Skælskør')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4241, N'Vemmelev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4242, N'Boeslunde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4243, N'Rude')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4250, N'Fuglebjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4261, N'Dalmose')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4262, N'Sandved')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4270, N'Høng')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4281, N'Gørlev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4291, N'Ruds Vedby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4293, N'Dianalund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4295, N'Stenlille')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4296, N'Nyrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4300, N'Holbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4320, N'Lejre')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4330, N'Hvalsø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4340, N'Tølløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4350, N'Ugerløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4360, N'Kirke Eskilstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4370, N'Store Merløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4390, N'Vipperød')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4400, N'Kalundborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4420, N'Regstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4440, N'Mørkøv')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4450, N'Jyderup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4460, N'Snertinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4470, N'Svebølle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4480, N'Store Fuglede')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4490, N'Jerslev Sjælland')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4500, N'Nykøbing Sj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4520, N'Svinninge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4532, N'Gislinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4534, N'Hørve')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4540, N'Fårevejle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4550, N'Asnæs')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4560, N'Vig')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4571, N'Grevinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4572, N'Nørre Asmindrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4573, N'Højby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4581, N'Rørvig')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4583, N'Sjællands Odde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4591, N'Føllenslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4592, N'Sejerø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4593, N'Eskebjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4600, N'Køge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4621, N'Gadstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4622, N'Havdrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4623, N'Lille Skensved')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4632, N'Bjæverskov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4640, N'Faxe')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4652, N'Hårlev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4653, N'Karise')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4654, N'Faxe Ladeplads')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4660, N'Store Heddinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4671, N'Strøby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4672, N'Klippinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4673, N'Rødvig Stevns')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4681, N'Herfølge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4682, N'Tureby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4683, N'Rønnede')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4684, N'Holmegaard ')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4690, N'Haslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4700, N'Næstved')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4720, N'Præstø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4733, N'Tappernøje')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4735, N'Mern')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4736, N'Karrebæksminde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4750, N'Lundby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4760, N'Vordingborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4771, N'Kalvehave')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4772, N'Langebæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4773, N'Stensved')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4780, N'Stege')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4791, N'Borre')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4792, N'Askeby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4793, N'Bogø By')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4800, N'Nykøbing F')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4840, N'Nørre Alslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4850, N'Stubbekøbing')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4862, N'Guldborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4863, N'Eskilstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4871, N'Horbelev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4872, N'Idestrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4873, N'Væggerløse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4874, N'Gedser')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4880, N'Nysted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4891, N'Toreby L')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4892, N'Kettinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4894, N'Øster Ulslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4895, N'Errindlev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4900, N'Nakskov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4912, N'Harpelunde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4913, N'Horslunde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4920, N'Søllested')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4930, N'Maribo')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4941, N'Bandholm')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4943, N'Torrig L')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4944, N'Fejø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4951, N'Nørreballe')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4952, N'Stokkemarke')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4953, N'Vesterborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4960, N'Holeby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4970, N'Rødby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4983, N'Dannemare')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4990, N'Sakskøbing')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (4992, N'Midtsjælland USF P')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5000, N'Odense C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5029, N'Odense C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5100, N'Odense C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5200, N'Odense V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5210, N'Odense NV')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5220, N'Odense SØ')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5230, N'Odense M')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5240, N'Odense NØ')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5250, N'Odense SV')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5260, N'Odense S')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5270, N'Odense N')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5290, N'Marslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5300, N'Kerteminde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5320, N'Agedrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5330, N'Munkebo')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5350, N'Rynkeby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5370, N'Mesinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5380, N'Dalby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5390, N'Martofte')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5400, N'Bogense')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5450, N'Otterup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5462, N'Morud')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5463, N'Harndrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5464, N'Brenderup Fyn')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5466, N'Asperup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5471, N'Søndersø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5474, N'Veflinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5485, N'Skamby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5491, N'Blommenslyst')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5492, N'Vissenbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5500, N'Middelfart')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5540, N'Ullerslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5550, N'Langeskov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5560, N'Aarup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5580, N'Nørre Aaby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5591, N'Gelsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5592, N'Ejby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5600, N'Faaborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5610, N'Assens')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5620, N'Glamsbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5631, N'Ebberup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5642, N'Millinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5672, N'Broby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5683, N'Haarby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5690, N'Tommerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5700, N'Svendborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5750, N'Ringe')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5762, N'Vester Skerninge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5771, N'Stenstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5772, N'Kværndrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5792, N'Årslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5800, N'Nyborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5853, N'Ørbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5854, N'Gislev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5856, N'Ryslinge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5863, N'Ferritslev Fyn')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5871, N'Frørup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5874, N'Hesselager')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5881, N'Skårup Fyn')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5882, N'Vejstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5883, N'Oure')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5884, N'Gudme')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5892, N'Gudbjerg Sydfyn')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5900, N'Rudkøbing')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5932, N'Humble')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5935, N'Bagenkop')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5953, N'Tranekær')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5960, N'Marstal')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5970, N'Ærøskøbing')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (5985, N'Søby Ærø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6000, N'Kolding')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6040, N'Egtved')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6051, N'Almind')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6052, N'Viuf')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6064, N'Jordrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6070, N'Christiansfeld')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6091, N'Bjert')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6092, N'Sønder Stenderup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6093, N'Sjølund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6094, N'Hejls')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6100, N'Haderslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6200, N'Aabenraa')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6230, N'Rødekro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6240, N'Løgumkloster')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6261, N'Bredebro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6270, N'Tønder')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6280, N'Højer')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6300, N'Gråsten')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6310, N'Broager')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6320, N'Egernsund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6330, N'Padborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6340, N'Kruså')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6360, N'Tinglev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6372, N'Bylderup-Bov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6392, N'Bolderslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6400, N'Sønderborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6430, N'Nordborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6440, N'Augustenborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6470, N'Sydals')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6500, N'Vojens')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6510, N'Gram')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6520, N'Toftlund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6534, N'Agerskov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6535, N'Branderup J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6541, N'Bevtoft')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6560, N'Sommersted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6580, N'Vamdrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6600, N'Vejen')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6621, N'Gesten')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6622, N'Bække')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6623, N'Vorbasse')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6630, N'Rødding')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6640, N'Lunderskov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6650, N'Brørup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6660, N'Lintrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6670, N'Holsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6682, N'Hovborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6683, N'Føvling')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6690, N'Gørding')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6700, N'Esbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6701, N'Esbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6705, N'Esbjerg Ø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6710, N'Esbjerg V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6715, N'Esbjerg N')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6720, N'Fanø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6731, N'Tjæreborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6740, N'Bramming')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6752, N'Glejbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6753, N'Agerbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6760, N'Ribe')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6771, N'Gredstedbro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6780, N'Skærbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6792, N'Rømø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6800, N'Varde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6818, N'Årre')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6823, N'Ansager')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6830, N'Nørre Nebel')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6840, N'Oksbøl')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6851, N'Janderup Vestj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6852, N'Billum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6853, N'Vejers Strand')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6854, N'Henne')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6855, N'Outrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6857, N'Blåvand')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6862, N'Tistrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6870, N'Ølgod')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6880, N'Tarm')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6893, N'Hemmet')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6900, N'Skjern')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6920, N'Videbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6933, N'Kibæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6940, N'Lem St')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6950, N'Ringkøbing')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6960, N'Hvide Sande')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6971, N'Spjald')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6973, N'Ørnhøj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6980, N'Tim')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (6990, N'Ulfborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7000, N'Fredericia')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7007, N'Fredericia')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7029, N'Fredericia')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7080, N'Børkop')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7100, N'Vejle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7120, N'Vejle Øst')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7130, N'Juelsminde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7140, N'Stouby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7150, N'Barrit')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7160, N'Tørring')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7171, N'Uldum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7173, N'Vonge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7182, N'Bredsten')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7183, N'Randbøl')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7184, N'Vandel')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7190, N'Billund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7200, N'Grindsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7250, N'Hejnsvig')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7260, N'Sønder Omme')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7270, N'Stakroge')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7280, N'Sønder Felding')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7300, N'Jelling')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7321, N'Gadbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7323, N'Give')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7330, N'Brande')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7361, N'Ejstrupholm')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7362, N'Hampen')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7400, N'Herning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7429, N'Herning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7430, N'Ikast')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7441, N'Bording')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7442, N'Engesvang')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7451, N'Sunds')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7470, N'Karup J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7480, N'Vildbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7490, N'Aulum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7500, N'Holstebro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7540, N'Haderup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7550, N'Sørvad')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7560, N'Hjerm')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7570, N'Vemb')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7600, N'Struer')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7620, N'Lemvig')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7650, N'Bøvlingbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7660, N'Bækmarksbro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7673, N'Harboøre')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7680, N'Thyborøn')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7700, N'Thisted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7730, N'Hanstholm')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7741, N'Frøstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7742, N'Vesløs')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7752, N'Snedsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7755, N'Bedsted Thy')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7760, N'Hurup Thy')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7770, N'Vestervig')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7790, N'Thyholm')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7800, N'Skive')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7830, N'Vinderup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7840, N'Højslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7850, N'Stoholm Jyll')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7860, N'Spøttrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7870, N'Roslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7884, N'Fur')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7900, N'Nykøbing M')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7950, N'Erslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7960, N'Karby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7970, N'Redsted M')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7980, N'Vils')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7990, N'Øster Assels')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7992, N'Sydjylland/Fyn USF P')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7993, N'Sydjylland/Fyn USF B')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7996, N'Fakturaservice')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7997, N'Fakturascanning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (7999, N'Kommunepost')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8000, N'Århus C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8100, N'Århus C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8200, N'Århus N')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8210, N'Århus V')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8220, N'Brabrand')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8229, N'Risskov Ø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8230, N'Åbyhøj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8240, N'Risskov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8245, N'Risskov Ø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8250, N'Egå')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8260, N'Viby J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8270, N'Højbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8300, N'Odder')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8305, N'Samsø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8310, N'Tranbjerg J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8320, N'Mårslet')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8330, N'Beder')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8340, N'Malling')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8350, N'Hundslund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8355, N'Solbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8361, N'Hasselager')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8362, N'Hørning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8370, N'Hadsten')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8380, N'Trige')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8381, N'Tilst')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8382, N'Hinnerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8400, N'Ebeltoft')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8410, N'Rønde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8420, N'Knebel')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8444, N'Balle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8450, N'Hammel')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8462, N'Harlev J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8464, N'Galten')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8471, N'Sabro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8472, N'Sporup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8500, N'Grenaa')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8520, N'Lystrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8530, N'Hjortshøj')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8541, N'Skødstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8543, N'Hornslet')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8544, N'Mørke')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8550, N'Ryomgård')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8560, N'Kolind')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8570, N'Trustrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8581, N'Nimtofte')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8585, N'Glesborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8586, N'Ørum Djurs')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8592, N'Anholt')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8600, N'Silkeborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8620, N'Kjellerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8632, N'Lemming')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8641, N'Sorring')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8643, N'Ans By')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8653, N'Them')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8654, N'Bryrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8660, N'Skanderborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8670, N'Låsby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8680, N'Ry')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8700, N'Horsens')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8721, N'Daugård')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8722, N'Hedensted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8723, N'Løsning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8732, N'Hovedgård')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8740, N'Brædstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8751, N'Gedved')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8752, N'Østbirk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8762, N'Flemming')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8763, N'Rask Mølle')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8765, N'Klovborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8766, N'Nørre Snede')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8781, N'Stenderup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8783, N'Hornsyld')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8800, N'Viborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8830, N'Tjele')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8831, N'Løgstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8832, N'Skals')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8840, N'Rødkærsbro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8850, N'Bjerringbro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8860, N'Ulstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8870, N'Langå')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8881, N'Thorsø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8882, N'Fårvang')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8883, N'Gjern')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8900, N'Randers C')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8920, N'Randers NV')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8930, N'Randers NØ')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8940, N'Randers SV')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8950, N'Ørsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8960, N'Randers SØ')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8961, N'Allingåbro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8963, N'Auning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8970, N'Havndal')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8981, N'Spentrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8983, N'Gjerlev J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (8990, N'Fårup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9000, N'Aalborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9029, N'Aalborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9100, N'Aalborg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9200, N'Aalborg SV')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9210, N'Aalborg SØ')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9220, N'Aalborg Øst')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9230, N'Svenstrup J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9240, N'Nibe')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9260, N'Gistrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9270, N'Klarup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9280, N'Storvorde')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9293, N'Kongerslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9300, N'Sæby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9310, N'Vodskov')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9320, N'Hjallerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9330, N'Dronninglund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9340, N'Asaa')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9352, N'Dybvad')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9362, N'Gandrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9370, N'Hals')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9380, N'Vestbjerg')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9381, N'Sulsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9382, N'Tylstrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9400, N'Nørresundby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9430, N'Vadum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9440, N'Aabybro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9460, N'Brovst')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9480, N'Løkken')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9490, N'Pandrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9492, N'Blokhus')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9493, N'Saltum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9500, N'Hobro')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9510, N'Arden')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9520, N'Skørping')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9530, N'Støvring')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9541, N'Suldrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9550, N'Mariager')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9560, N'Hadsund')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9574, N'Bælum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9575, N'Terndrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9600, N'Aars')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9610, N'Nørager')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9620, N'Aalestrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9631, N'Gedsted')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9632, N'Møldrup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9640, N'Farsø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9670, N'Løgstør')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9681, N'Ranum')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9690, N'Fjerritslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9700, N'Brønderslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9740, N'Jerslev J')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9750, N'Østervrå')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9760, N'Vrå')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9800, N'Hjørring')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9830, N'Tårs')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9850, N'Hirtshals')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9870, N'Sindal')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9881, N'Bindslev')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9900, N'Frederikshavn')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9940, N'Læsø')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9970, N'Strandby')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9981, N'Jerup')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9982, N'Ålbæk')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9990, N'Skagen')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9992, N'Jylland USF P')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9993, N'Jylland USF B')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9996, N'Fakturaservice')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9997, N'Fakturascanning')
INSERT [dbo].[TP_Zip_City] ([zip], [city]) VALUES (9998, N'Borgerservice')
