use dm71_2
insert into frequency values(3, 1, 'ved hovedmåltider','1999-01-01')
insert into frequency values(6, 2, 'ved hovedmåltider','2000-01-01')
insert into frequency values(2, 1, 'morgen og aften','2001-11-11')
insert into frequency values(4, 2, 'morgen og aften','2002-02-12')
insert into frequency values(8, 2, 'ved hovedmåltider og lige inden sengetid','2003-03-23')

insert into car values('WW 12345','Citroén Berlingo')
insert into car values('XX 54321','Fiat Uno')
insert into car values('ZZ 12121','Mitsubishi Colt')
insert into car values('QQ 99999','Folkevognsrugbrød')
insert into car values('YY 23456','Ford Fiesta')

insert into externalcontact values('34567', 'læge', 'Peter', '', 'Frodin', 'Yogade 3', 1164, 98765432, 'wkjeb@khut.dk')
insert into externalcontact values('12345', 'læge', 'Jens', '', 'Jensen', 'Sygehusvej 32', 1163, 98333333, 'jensj@khat.dk')
insert into externalcontact values('76543', 'psykiater', 'Lars', 'L.', 'Larsen', 'Ankergade 44', 498, 11111111, 'lll@psyko.dk')
insert into externalcontact values('76859', 'psykolog', 'Knud', 'Børge', 'Børgesen', 'Kontrolvej 17', 1118, 66666666, 'knudbørge@psyko.dk')
insert into externalcontact values('98123', 'sagbehandler', 'Yvonne', '', 'Jensen', 'Ankergade 44', 581, 11111111, 'detsirjegdig@kommunen.dk')

insert into client values('Hans123456', 'Hahaha', 'Han er grim', 'Hans udseende er ikk for godt', '123456-7899', 'Hans', null, 'Pilgaard', 'Hahavej 13', 1164, 12345678, 'gj@ha.dk', '1999-01-01', 'Yes', null)
insert into client values('Ib234567', 'Blablabla', 'Glad for biler', 'Han får psykopharma', '234567-7891', 'Ib', null, 'Fusentast', 'Hahavej 14', 1164, 87654321, 'if@ha.dk', '2005-01-31', 'Yes', null)
insert into client values('Peter345678', 'Blablabla', 'Spiller fodbold', 'Han mangler venstre arm', '345678-7891', 'Peter', null, 'Pedal', 'Hahavej 15', 1164, 23456789, 'pp@ha.dk', '2007-01-21', 'Yes', null)
insert into client values('Johan456789', 'Blablabla', 'Spiller WOW', 'Han er diabetiker', '456789-7891', 'Johannes', null, 'Johansen', 'Hahavej 16', 1164, 87654321, 'jj@ha.dk', '2002-11-01', 'Yes', null)
insert into client values('Keld987654', 'Blablabla', 'Er glad for mad', 'Han er for tyk', '987654-7891', 'Keld', null, 'Jensen', 'Hahavej 17', 1164, 56789098, 'kj@ha.dk', '2010-11-25', 'Yes', null)
insert into client values('Egon123456', 'Blablabla', 'Kan godt lide pengeskabe', 'Han er frisk som en havørn', '123456-7893', 'Egon', null, 'Olsen', 'Hahavej 18', 1164, 43212345, 'eo@ha.dk', '2001-10-01', 'Yes', null)

insert into Employee values('1', '123', null, 'Chief', 'Yes', 'Yes' , 'Yes' ,'Yes', '123456-7895', 'Jacob', '', 'Glerup', 'Dannebrogsgade 63', 1118, 98673290, 'glerup9@hotmail.com', '2009.01.01', 'Yes', null)
insert into Employee values('2', '123', '1', 'Kakkelak', 'No', 'No' , 'No' , 'No', '123456-7891', 'Kristian', '', 'Byrialsen', 'Dannebrogsgade 11', 1118, 98673291, 'krbyr@hotmail.com', '01.01.1999', 'Yes', null)
insert into Employee values('3', '123', '1', 'Kakkelak2', 'No', 'No' , 'No' , 'No','123456-7893', 'Erik', 'Montegarlo', 'Gravesen', 'Gammelnibevej 4', 1125, 98673292, 'ervaerik@hotmail.com', '11.20.2010', 'Yes', null)
insert into Employee values('Inga123456', '123', '1', 'Teamleder', 'No', 'No' , 'Yes' ,'Yes', '123456-7894', 'Inga', '', 'Karlsson', 'Kandevej 1', 1164, 98673293, 'inga@notmail.com', '2009.01.01', 'Yes', null)
insert into Employee values('Krist123456', '123', 'Inga123456', 'Pædagog', 'No', 'No' , 'No' , 'No', '123456-7892', 'Kristina', '', 'Krølben', 'Krybevej', 1163, 98673294, 'krist@notmail.com', '12.01.1999', 'Yes', null)
insert into Employee values('Erika123456', '123', 'Inga123456', 'Hjemmehosser', 'No', 'No' , 'No' , 'No','123456-7896', 'Erika', 'Kan', 'Godt', 'Kanikkevej', 1118, 98673295, 'erika@notmail.com', '11.15.2010', 'Yes', null)

insert into medicine values(1, 1, 1, 'Fycidin', 'Bekæmper bakterier', '2010-01-01', 30)
insert into medicine values(2, 2, 2, 'Fydada', 'Psykopharma', '2010-01-01', 42)
insert into medicine values(3, 3, 3, 'Fyhaa', 'Mod acne', '2010-01-01', 50)
insert into medicine values(4, 1, 4, 'Fyføj', 'Ved diabetes', '2010-01-01', 44)
insert into medicine values(5, 2, 5, 'Fyhada', 'Opkvikkende', '2010-01-01', 80)
insert into medicine values(1, 3, 6, 'Fyføjda', 'Beroligende', '2010-01-01', 60)
insert into medicine values(2, 1, 1, 'Fyforden', 'Blodtryksmedicin', '2010-01-01', 60)
insert into medicine values(3, 2, 2, 'Fyfor', 'Mod smerter', '2010-01-01', 40)
insert into medicine values(4, 3, 3, 'Fyfordenda', 'Mod fantomsmerter', '2010-01-01', 40)

insert into dailyreport values(1, 1, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-10')
insert into dailyreport values(3, 2, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-10')
insert into dailyreport values(2, 3, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-10')
insert into dailyreport values(2, 1, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-11')
insert into dailyreport values(3, 3, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-11')
insert into dailyreport values(1, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-11')
insert into dailyreport values(3, 1, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-12')
insert into dailyreport values(2, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-12')
insert into dailyreport values(1, 3, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-12')
insert into dailyreport values(4, 4, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-12')
insert into dailyreport values(6, 5, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-12')
insert into dailyreport values(5, 6, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-12')
insert into dailyreport values(4, 1, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-13')
insert into dailyreport values(5, 4, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-13')
insert into dailyreport values(6, 6, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-13')
insert into dailyreport values(5, 1, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-14')
insert into dailyreport values(6, 4, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-14')
insert into dailyreport values(4, 5, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-14')
insert into dailyreport values(6, 1, 'Og endnu meget mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-15')
insert into dailyreport values(5, 5, 'Og endnu meget mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-15')
insert into dailyreport values(4, 6, 'Og endnu meget mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-15')

insert into reservation values(1,1,2,'2011-01-20','2011-01-20','2010-10-01')
insert into reservation values(2,2,3,'2011-01-21','2011-01-21','2010-10-02')
insert into reservation values(3,3,1,'2011-01-22','2011-01-22','2010-10-03')
insert into reservation values(4,1,6,'2011-01-22','2011-01-22','2010-10-04')
insert into reservation values(5,5,4,'2011-01-21','2011-01-21','2010-10-05')
insert into reservation values(2,3,2,'2011-01-22','2011-01-22','2010-10-06')
insert into reservation values(3,1,4,'2011-01-21','2011-01-21','2010-10-07')

insert into externaldocument values(1,'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-07', 'Kommunen', 'Yvonne Jensen')
insert into externaldocument values(2,'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-08', 'Psykiatrisk afdeling', 'Karl Børge')
insert into externaldocument values(3,'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-09', 'Lægen', 'Svend Bendt')
insert into externaldocument values(4,'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-10', 'Chokoladefabrikken', 'Chris Dis')
insert into externaldocument values(5,'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-11', 'Kommunen', 'Brian Igenigen')
insert into externaldocument values(6,'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla. Blablabla blabla bla bla blabla bla. Blabla bla blablabla blabla bla, bla bla blabla bla.', '2010-10-12', 'Psykiatrisk afdeling', 'Karl Smart')

insert into milestone values(1,'Hoppe på et ben','2010-10-01', null)
insert into milestone values(1,'Røgfri','2010-10-02', null)
insert into milestone values(1,'Bygge med lego','2010-10-03', null)
insert into milestone values(2,'Køre bil','2010-10-03', null)
insert into milestone values(3,'Røgfri','2010-10-04', null)
insert into milestone values(4,'Bygge med lego','2010-10-06', '2010-12-30')
insert into milestone values(4,'Lave saltomotaler','2010-10-07', null)
insert into milestone values(5,'Lave saltomotaler','2010-10-10', null)
insert into milestone values(6,'Spise med kniv og gaffel','2010-10-11', null)
insert into milestone values(6,'Røgfri','2010-10-12', null)

insert into milestone_update values(1, 2, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(2, 2, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(3, 2, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(4, 1, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(5, 3, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(6, 4, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(7, 4, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(8, 5, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(9, 6, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(10, 6, 'Blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-01')
insert into milestone_update values(1, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(2, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(3, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(4, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(5, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(6, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(7, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(8, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(9, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(10, 2, 'Mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-02')
insert into milestone_update values(1, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(2, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(3, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(4, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(5, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(6, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(7, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(8, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(9, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')
insert into milestone_update values(10, 2, 'Endnu mere blabla bla blabla bla. Blabla bla bla, bal Bla blabla blablabla.','2010-11-03')

insert into errorhandlingmedicine values(1, 1, 2, '2010-06-14', 'Tabt pille på gulvet', 1)
insert into errorhandlingmedicine values(3, 3, 1, '2010-07-09', 'Glemt piller', -3)
insert into errorhandlingmedicine values(2, 2, 1, '2010-08-11', 'Hunden spiste pillerne', 7)
insert into errorhandlingmedicine values(6, 6, 4, '2010-09-30', 'Pille mangler ved optælling', 1)
insert into errorhandlingmedicine values(9, 4, 5, '2010-10-21', 'For mange piller ved optælling', -2)
insert into errorhandlingmedicine values(7, 1, 3, '2010-11-01', 'Pillen trillede ned i vasken', 1)
insert into errorhandlingmedicine values(2, 2, 3, '2010-12-15', 'Glemt pille', -1)
	
insert into client_externalcontact values(1,1)
insert into client_externalcontact values(1,4)
insert into client_externalcontact values(2,2)
insert into client_externalcontact values(2,5)
insert into client_externalcontact values(3,3)
insert into client_externalcontact values(3,4)
insert into client_externalcontact values(4,1)
insert into client_externalcontact values(4,5)
insert into client_externalcontact values(5,2)
insert into client_externalcontact values(5,4)
insert into client_externalcontact values(6,3)
insert into client_externalcontact values(6,5)
				
insert into employee_client values(1, 1)
insert into employee_client values(1, 2)
insert into employee_client values(1, 3)
insert into employee_client values(1, 4)
insert into employee_client values(1, 5)
insert into employee_client values(1, 6)
insert into employee_client values(2, 1)	
insert into employee_client values(2, 2)
insert into employee_client values(2, 3)
insert into employee_client values(3, 1)
insert into employee_client values(3, 2)
insert into employee_client values(3, 3)
insert into employee_client values(4, 4)
insert into employee_client values(4, 5)	
insert into employee_client values(4, 6)
insert into employee_client values(5, 4)
insert into employee_client values(5, 5)
insert into employee_client values(5, 6)
insert into employee_client values(6, 4)
insert into employee_client values(6, 5)
insert into employee_client values(6, 6)	
	